In [1]:
import pandas as pd
import sys

sys.path.insert(0, '../raw_data_elaboration')

import data_processing_library as dpl

2025-03-20 14:00:05.731511: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1742475605.748523 2397507 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1742475605.753774 2397507 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-20 14:00:05.770989: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
meta = dpl.load_dataframe("/home/lukovic/data/treenet/server_data/metadata.pkl")
dendro = dpl.load_dataframe("/home/lukovic/data/treenet/server_data/data_dendro_lm.pkl")
clima = dpl.load_dataframe("/home/lukovic/data/treenet/server_data/data_meteo_l2.pkl")

In [ ]:
meta

,measure_point,series_id,series_start,series_stop,series_cutout,series_active,series_display,variable_id,variable_name,variable_resolution,...,site_annual_rad,site_growth_rad,site_annual_relh,site_growth_relh,site_annual_vpd,site_growth_vpd,site_n_depo,site_ozon,site_nfk,site_temp_ref
0,alvaneu-high_dendrometer_µm_n3_0_1.5_south_psy...,1,2014-05-21,2022-10-05,None,no,no,3,tree stem radius change,10,...,166.52,243.83,70.81,70.57,0.30,0.48,None,None,106.00,1178.0
1,alvaneu-high_dendrometer_µm_n4_0_1.5_south_psy...,2,2014-05-21,2022-10-05,None,no,no,3,tree stem radius change,10,...,166.52,243.83,70.81,70.57,0.30,0.48,None,None,106.00,1178.0
2,alvaneu-low_dendrometer_µm_n1_0_1.5_south_psyl...,3,2014-05-21,2022-10-05,None,no,no,3,tree stem radius change,10,...,164.93,239.27,70.23,69.62,0.33,0.51,None,None,191.00,1178.0
3,alvaneu-low_dendrometer_µm_n2_0_1.5_south_psyl...,4,2014-05-21,2022-10-05,None,no,no,3,tree stem radius change,10,...,164.93,239.27,70.23,69.62,0.33,0.51,None,None,191.00,1178.0
4,bachtel-forest_precipitation_mm_meteo_-999_2_b...,5,2012-08-24,2022-09-28,None,no,no,10,precipitation,10,...,137.28,223.03,77.13,74.20,0.30,0.50,None,None,None,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1853,mund-dry_soil_wp_kpa_-999_-999_-15_soil_--999,1873,2024-05-29,NaT,None,yes,yes,32,soil water potential,10,...,164.11,255.25,68.01,63.29,0.45,0.75,None,None,None,1722.0
1854,mund-dry_soil_temp_°c_-999_-999_-50_soil_--999,1874,2024-05-29,NaT,None,yes,yes,29,soil temperature,10,...,164.11,255.25,68.01,63.29,0.45,0.75,None,None,None,1722.0
1855,mund-dry_soil_wp_kpa_-999_-999_-50_soil_--999,1875,2024-05-29,NaT,None,yes,yes,32,soil water potential,10,...,164.11,255.25,68.01,63.29,0.45,0.75,None,None,None,1722.0
1856,mund-dry_soil_temp_°c_-999_-999_-100_soil_--999,1876,2024-05-29,NaT,None,yes,yes,29,soil temperature,10,...,164.11,255.25,68.01,63.29,0.45,0.75,None,None,None,1722.0
1857,mund-dry_soil_wp_kpa_-999_-999_-100_soil_--999,1877,2024-05-29,NaT,None,yes,yes,32,soil water potential,10,...,164.11,255.25,68.01,63.29,0.45,0.75,None,None,None,1722.0

In [13]:
meta_id = {}
for index, row in meta.iterrows():    
    print(row.series_id, row.site_id)
    meta_id[row.series_id] = row

1 1
2 1
3 2
4 2
5 3
6 3
7 3
8 3
9 3
10 3
11 3
12 3
13 3
14 3
15 3
16 3
17 3
18 3
19 3
20 3
21 3
22 3
23 3
24 3
25 4
26 4
27 4
28 4
29 4
30 4
31 4
32 4
33 4
34 4
35 5
36 5
37 5
38 6
39 6
40 6
41 6
42 7
43 7
44 7
45 8
46 8
47 8
48 9
49 9
50 9
51 10
52 10
53 10
54 10
55 10
56 10
57 10
58 10
59 10
60 10
61 10
62 10
63 10
64 10
65 10
66 10
67 10
68 10
69 10
70 10
71 10
72 10
73 10
74 10
75 10
76 10
77 10
78 10
79 10
80 10
81 10
82 10
83 10
84 10
85 10
86 11
87 11
88 11
89 11
90 12
91 12
92 12
93 13
94 13
95 14
96 14
97 14
98 15
99 15
100 15
101 16
102 16
103 16
104 17
105 17
106 17
107 18
108 18
109 19
110 19
111 19
112 20
113 20
114 20
115 21
116 21
117 21
118 22
119 22
120 22
121 22
122 23
123 23
124 23
125 23
126 23
127 23
128 23
129 134
130 23
131 23
132 23
133 23
134 134
135 23
136 23
137 23
138 23
139 23
140 24
141 24
142 24
144 25
145 25
147 26
148 26
149 26
150 27
151 27
152 27
153 28
154 28
155 28
156 29
157 29
158 30
159 30
160 30
161 30
162 31
163 31
164 32
165 32
166 32
167 32
168 32
169 32
170 33
171 33
172 33
173 33
174 34
175 34
176 34
177 34
178 34
179 34
180 34
181 34
182 34
183 34
184 34
185 34
186 34
187 34
188 34
189 34
190 34
191 34
192 34
193 34
194 34
195 34
196 35
197 35
198 35
199 35
200 35
201 35
202 35
203 35
204 35
205 35
206 35
207 35
208 35
209 36
210 36
211 36
212 36
213 36
214 36
215 36
216 36
217 36
218 36
219 36
220 36
221 36
222 36
223 36
224 36
225 36
226 36
227 36
228 36
229 36
230 36
231 36
232 36
233 36
234 36
235 36
236 36
237 36
238 36
239 36
240 36
241 36
242 36
243 36
244 36
245 36
246 36
247 36
248 36
249 36
250 36
251 36
252 36
253 36
254 36
255 36
256 36
257 36
258 36
259 36
260 36
261 36
262 36
263 36
264 36
265 36
266 36
267 36
268 36
269 36
270 36
271 36
272 36
273 36
274 36
275 36
276 36
277 36
278 36
279 36
280 36
281 36
282 36
283 36
284 36
285 36
286 36
287 36
288 36
289 36
290 36
291 36
292 36
293 36
294 36
295 36
296 36
297 36
298 36
299 36
300 36
301 36
302 36
303 36
304 36
305 36
306 36
307 36
308 36
309 36
310 36
311 36
312 36
313 36
314 36
315 36
316 36
317 36
318 36
319 36
320 36
321 36
322 36
323 36
324 36
325 36
326 36
327 36
328 36
329 36
330 36
331 36
332 36
333 36
334 36
335 36
336 36
337 36
338 36
339 36
340 36
341 36
342 36
343 36
344 36
345 36
346 36
347 36
348 36
349 36
350 36
351 36
352 36
353 36
354 36
355 36
356 36
357 36
358 36
359 36
360 36
361 37
362 37
363 37
364 38
365 38
366 38
367 38
368 39
369 39
370 39
371 40
372 40
373 40
374 41
375 41
376 41
377 42
378 42
379 42
380 42
381 42
382 42
383 42
384 42
385 42
386 42
387 42
388 42
389 42
390 42
391 42
392 42
393 42
394 42
395 42
396 42
397 42
398 42
399 43
400 43
401 43
402 43
403 43
404 43
405 43
406 43
407 43
408 43
409 43
410 43
411 43
412 43
413 43
414 43
415 43
416 43
417 43
418 43
419 43
420 44
421 44
422 44
423 44
424 44
425 44
426 44
427 44
428 44
429 44
430 44
431 44
432 44
433 44
434 44
435 44
436 44
437 44
438 44
439 44
440 44
441 44
442 44
443 44
444 44
445 44
446 44
447 44
448 44
449 45
450 45
451 45
452 45
453 45
454 45
455 45
456 45
457 45
458 45
459 45
460 45
461 45
462 45
463 45
464 45
465 45
466 45
467 45
468 45
469 45
470 45
471 45
472 45
473 45
474 45
475 45
476 45
477 45
478 45
479 45
480 45
481 45
482 45
483 45
484 45
485 45
486 45
487 45
488 45
490 45
491 45
492 45
493 45
494 45
495 45
496 45
497 45
498 45
499 45
500 45
501 45
502 45
503 45
504 45
505 45
506 45
507 45
508 45
509 45
510 45
511 45
512 45
513 45
514 45
515 45
516 45
517 45
518 45
519 45
520 45
521 45
522 45
523 45
524 45
525 45
526 45
527 45
528 45
529 45
530 45
531 45
532 45
533 45
534 45
535 45
536 45
537 46
538 46
539 46
540 46
541 46
542 46
543 46
544 46
545 46
546 46
547 46
548 46
549 46
550 46
551 46
552 46
553 46
554 46
555 47
556 47
557 47
558 47
559 48
560 48
561 48
562 48
563 48
564 48
565 48
566 48
567 48
568 48
569 48
570 49
571 49
572 49
573 49
574 49
575 49
576 49
577 49
578 49
579 49
580 50
581 50
582 50
583 50
584 50
585 50
586 50
587 50
588 50
589 50
590 50
591 50
592 50
593 50
594 50
595 50
596 50
597 50
598 50
599 50
600 50
601 50
602 50
603 50
604 50
605 51
606 51
607 51
608 51
609 51
610 51
611 51
612 51
613 51
614 51
615 51
616 51
617 51
618 51
619 51
620 51
621 51
622 51
623 51
624 51
625 51
626 51
627 51
628 51
629 51
630 51
631 51
632 51
633 51
634 51
635 51
636 51
637 51
638 51
639 51
640 51
641 51
642 51
643 51
644 51
645 51
646 51
647 51
648 51
649 51
650 51
651 51
652 51
653 51
654 51
655 51
656 51
657 51
658 51
659 51
660 51
661 51
662 51
663 51
664 51
665 51
666 51
667 51
668 51
669 51
670 51
671 51
672 51
673 51
674 51
675 51
676 51
677 51
678 51
679 51
680 51
681 51
682 51
683 51
684 51
685 51
686 52
687 52
688 52
689 52
690 52
691 52
692 52
693 52
694 52
695 52
696 53
697 53
698 53
699 53
700 54
701 54
702 54
703 54
704 54
705 54
706 54
707 54
708 54
709 54
710 54
711 54
712 55
713 55
714 55
715 55
716 56
717 56
718 57
719 57
720 57
721 57
722 57
723 57
724 57
725 57
726 57
727 57
728 57
729 57
730 58
731 58
732 58
733 58
734 58
735 58
736 59
737 59
738 60
739 60
740 60
741 60
742 60
743 60
744 60
745 60
746 60
747 60
748 60
749 60
750 61
751 61
752 61
753 61
754 61
755 61
756 62
757 62
758 62
759 62
760 62
761 62
762 62
763 62
764 62
765 62
766 62
767 62
768 63
769 63
770 64
771 64
772 64
773 64
774 64
775 64
776 64
777 64
778 65
779 65
780 65
781 65
782 66
783 66
784 66
785 66
786 66
787 66
788 66
789 66
790 66
791 66
792 66
793 66
794 67
795 67
796 67
797 67
798 67
799 67
800 68
801 68
802 68
803 68
804 68
805 68
806 68
807 68
808 69
809 69
810 69
811 69
812 69
813 69
814 70
815 70
816 70
817 70
818 70
819 70
820 70
821 70
822 70
823 70
824 70
825 70
826 70
827 70
828 70
829 70
830 70
831 70
832 70
833 70
834 70
835 70
836 70
837 70
838 70
839 71
840 71
841 71
842 71
843 71
844 71
845 71
846 71
847 72
848 72
849 72
850 72
851 73
852 73
853 73
854 73
855 74
856 74
857 75
858 75
859 75
860 75
861 75
862 75
863 75
864 75
865 75
866 75
867 75
868 75
869 75
870 75
871 75
872 75
873 75
874 75
875 75
876 75
877 75
878 75
879 75
880 75
881 75
882 75
883 76
884 76
885 76
886 77
887 77
888 78
889 78
890 78
891 79
892 79
893 79
894 80
895 80
896 80
897 81
898 81
899 81
900 82
901 82
902 83
903 83
904 83
905 84
906 84
907 84
908 85
909 85
910 85
911 86
912 86
913 86
914 86
915 86
916 86
917 86
918 86
919 86
920 86
921 86
922 86
923 86
924 86
925 86
926 86
927 86
928 86
929 86
930 86
931 86
932 86
933 86
934 86
935 86
936 86
937 86
938 86
939 86
940 86
941 86
942 86
943 86
944 86
945 86
946 86
947 86
948 86
949 86
950 86
951 86
952 86
953 86
954 86
955 86
956 86
957 86
958 86
959 86
960 86
961 86
962 86
963 86
964 87
965 87
966 87
967 87
968 88
969 88
970 88
971 88
972 89
973 89
974 89
975 89
976 89
977 89
978 89
979 89
980 89
981 89
982 89
983 89
984 89
985 89
986 89
987 89
988 89
989 89
990 89
991 89
992 89
993 89
994 89
995 89
996 89
997 89
998 89
999 89
1000 89
1001 89
1002 89
1003 89
1004 89
1005 89
1006 89
1007 90
1008 90
1009 90
1010 90
1011 90
1012 90
1013 90
1014 90
1015 90
1016 90
1017 90
1018 90
1019 90
1020 90
1021 90
1022 90
1023 90
1024 90
1025 90
1026 90
1027 90
1028 90
1029 90
1030 90
1031 90
1032 90
1033 90
1034 90
1035 90
1036 90
1037 90
1038 90
1039 90
1040 90
1041 90
1042 90
1043 90
1044 90
1045 90
1046 90
1047 90
1048 90
1049 90
1050 91
1051 91
1052 91
1053 91
1054 91
1055 91
1056 91
1057 91
1058 91
1059 91
1060 92
1061 92
1062 92
1063 92
1064 92
1065 92
1066 92
1067 93
1068 93
1069 93
1070 93
1071 93
1072 93
1073 93
1074 93
1075 93
1076 93
1077 94
1078 94
1079 94
1080 94
1081 94
1082 94
1083 95
1084 95
1085 95
1086 95
1087 95
1088 95
1089 95
1090 95
1091 95
1092 96
1093 96
1094 96
1095 96
1096 96
1097 96
1098 96
1099 96
1100 96
1101 96
1102 96
1103 96
1104 96
1105 96
1106 96
1107 96
1108 97
1109 97
1110 97
1111 97
1112 97
1113 97
1114 97
1115 97
1116 97
1117 97
1118 98
1119 98
1120 98
1121 98
1122 98
1123 98
1124 98
1125 98
1126 98
1127 98
1128 98
1129 98
1130 98
1131 98
1132 98
1133 98
1134 98
1135 98
1136 98
1137 98
1138 98
1139 98
1140 98
1141 98
1142 98
1143 98
1144 98
1145 98
1146 98
1147 99
1148 99
1149 99
1150 99
1151 99
1152 99
1153 99
1154 99
1155 99
1156 99
1157 99
1158 99
1159 99
1160 99
1161 99
1162 100
1163 100
1164 100
1165 100
1166 100
1167 101
1168 101
1169 101
1170 101
1171 101
1172 102
1173 102
1174 102
1175 102
1176 102
1177 102
1178 102
1179 102
1180 102
1181 102
1182 102
1183 102
1184 102
1185 102
1186 102
1187 102
1188 102
1189 102
1190 102
1191 102
1192 102
1193 102
1194 102
1195 102
1196 102
1197 102
1198 102
1199 102
1200 102
1201 102
1202 102
1203 102
1204 103
1205 103
1206 103
1207 103
1208 103
1209 103
1210 104
1211 104
1212 105
1213 105
1214 105
1215 105
1216 105
1217 105
1218 105
1219 105
1220 105
1221 105
1222 105
1223 105
1224 105
1225 105
1226 105
1227 105
1228 105
1229 105
1230 106
1231 106
1232 106
1233 106
1234 106
1235 106
1236 106
1237 106
1238 107
1239 107
1240 107
1241 107
1242 107
1243 107
1244 107
1245 107
1246 107
1247 107
1248 107
1249 107
1250 107
1251 107
1252 108
1253 108
1254 108
1255 108
1256 108
1257 108
1258 108
1259 108
1260 108
1261 108
1262 108
1263 108
1264 108
1265 108
1266 109
1267 109
1268 109
1269 109
1270 109
1271 109
1272 109
1273 109
1274 110
1275 110
1276 110
1277 110
1278 110
1279 110
1280 111
1281 111
1282 111
1283 111
1284 111
1285 111
1286 111
1287 111
1288 111
1289 111
1290 111
1291 112
1292 112
1293 112
1294 112
1295 112
1296 112
1297 112
1298 112
1299 112
1300 112
1301 112
1302 113
1303 113
1304 113
1305 113
1306 113
1307 113
1308 113
1309 113
1310 113
1311 113
1312 113
1313 114
1314 114
1315 114
1316 114
1317 115
1318 115
1319 115
1320 115
1321 115
1322 115
1323 115
1324 115
1325 115
1326 115
1327 115
1328 116
1329 116
1330 116
1331 116
1332 116
1333 116
1334 116
1335 116
1336 116
1337 116
1338 116
1339 116
1340 117
1341 117
1342 117
1343 117
1344 117
1345 117
1346 117
1347 117
1348 117
1349 117
1350 117
1351 118
1352 118
1353 118
1354 118
1355 118
1356 118
1357 118
1358 118
1359 118
1360 118
1361 118
1362 118
1363 118
1364 118
1365 119
1366 119
1367 119
1368 119
1369 119
1370 119
1371 119
1372 119
1373 119
1374 119
1375 119
1376 119
1377 119
1378 119
1379 120
1380 120
1381 120
1382 120
1383 120
1384 120
1385 120
1386 120
1387 121
1388 121
1389 121
1390 121
1391 121
1392 121
1393 121
1394 121
1395 121
1396 121
1397 121
1398 121
1399 122
1400 122
1401 122
1402 122
1403 122
1404 122
1405 122
1406 122
1407 122
1408 122
1409 123
1410 123
1411 123
1412 124
1413 124
1414 125
1415 125
1416 125
1417 126
1418 126
1419 126
1420 127
1421 127
1422 127
1423 128
1424 128
1425 128
1427 129
1428 129
1430 130
1431 130
1432 130
1433 131
1434 131
1435 131
1436 132
1437 132
1438 132
1439 133
1440 134
1441 134
1442 134
1443 134
1444 134
1445 134
1446 134
1447 134
1448 134
1449 134
1450 134
1451 134
1452 134
1453 134
1454 134
1455 135
1456 135
1457 135
1458 135
1459 135
1460 135
1461 135
1462 135
1463 135
1464 135
1465 135
1466 136
1467 136
1468 136
1469 136
1470 137
1471 137
1472 137
1473 137
1474 137
1475 137
1476 137
1477 137
1478 137
1479 138
1480 138
1481 138
1482 138
1483 138
1484 138
1485 138
1486 138
1487 138
1488 138
1489 138
1490 139
1491 139
1492 139
1493 139
1494 139
1495 139
1496 139
1497 139
1498 139
1499 139
1500 139
1501 140
1502 140
1503 140
1504 140
1505 140
1506 140
1507 140
1508 140
1509 140
1510 140
1511 140
1512 141
1513 141
1514 141
1515 141
1516 142
1517 142
1518 142
1519 142
1520 142
1521 142
1522 142
1523 142
1524 142
1525 142
1526 142
1527 143
1528 143
1529 143
1530 143
1531 143
1532 143
1533 143
1534 143
1535 143
1536 144
1537 144
1538 144
1539 144
1540 144
1541 144
1542 144
1543 144
1544 144
1545 144
1546 144
1547 86
1548 86
1549 86
1550 86
1551 86
1552 86
1553 86
1554 86
1555 86
1556 90
1557 90
1558 90
1559 90
1560 90
1561 90
1562 90
1563 90
1564 90
1565 145
1566 145
1567 145
1568 145
1569 145
1570 145
1571 145
1572 145
1573 145
1574 146
1575 146
1576 146
1577 146
1578 146
1579 146
1580 146
1581 146
1582 146
1583 147
1584 147
1585 147
1586 147
1587 147
1588 147
1589 147
1590 147
1591 147
1592 95
1593 95
1594 86
1595 86
1596 86
1597 86
1598 105
1599 105
1600 157
1601 157
1602 157
1603 160
1604 160
1605 160
1606 160
1607 160
1608 157
1609 157
1610 157
1611 157
1612 157
1613 157
1614 157
1615 160
1616 160
1617 160
1618 157
1619 157
1620 43
1621 43
1622 43
1623 43
1624 43
1625 43
1626 161
1627 161
1628 162
1629 162
1630 161
1631 161
1632 161
1633 161
1634 161
1635 161
1636 162
1637 162
1638 162
1639 163
1640 163
1641 163
1642 163
1643 163
1644 163
1645 164
1646 164
1647 164
1648 164
1649 164
1650 164
1651 164
1652 164
1653 164
1654 164
1655 164
1656 164
1657 164
1658 164
1659 164
1660 164
1661 165
1662 165
1663 165
1664 165
1665 165
1666 165
1667 165
1668 165
1669 165
1670 165
1671 165
1672 165
1673 165
1674 165
1675 166
1676 166
1677 166
1678 166
1679 166
1680 166
1681 166
1682 166
1683 166
1684 166
1685 166
1686 166
1687 166
1688 166
1689 157
1690 157
1691 157
1692 157
1693 167
1694 167
1695 167
1696 167
1697 167
1698 167
1699 167
1700 167
1701 167
1702 167
1703 167
1704 167
1705 167
1706 167
1707 167
1708 167
1709 160
1710 160
1711 160
1712 160
1713 160
1714 160
1715 160
1716 163
1717 164
1718 165
1719 166
1720 167
1721 160
1722 163
1723 164
1724 165
1725 166
1726 167
1727 146
1728 129
1729 25
1730 25
1731 129
1732 157
1733 157
1734 157
1735 157
1736 157
1737 157
1738 157
1739 157
1740 157
1741 157
1742 157
1743 157
1744 160
1745 160
1746 160
1747 160
1748 160
1749 160
1750 160
1751 160
1752 160
1753 160
1754 160
1755 160
1756 164
1757 164
1758 166
1759 166
1760 166
1761 166
1762 166
1763 166
1764 164
1765 164
1766 164
1767 164
1768 164
1769 164
1770 166
1771 166
1772 166
1773 166
1774 166
1775 166
1776 164
1777 164
1778 164
1779 164
1780 167
1781 167
1782 167
1783 167
1784 167
1785 167
1786 167
1787 167
1788 167
1789 167
1790 167
1791 167
1792 165
1793 165
1794 165
1795 165
1796 165
1797 165
1798 165
1799 165
1800 165
1801 165
1802 165
1803 165
1805 5
1806 10
1807 90
1808 13
1809 14
1810 19
1811 118
1812 118
1813 118
1814 118
1815 118
1816 118
1817 118
1820 134
1821 36
1826 34
1827 34
1828 49
1829 49
1830 101
1831 22
1832 22
1833 22
1834 22
1835 22
1836 22
1837 169
1838 169
1839 169
1840 169
1841 169
1842 169
1843 169
1844 169
1845 170
1846 170
1847 170
1848 170
1849 170
1850 170
1851 170
1852 170
1853 171
1854 171
1855 171
1856 171
1857 171
1858 50
1859 146
1860 44
1866 44
1869 43
1870 44
1871 44
1872 163
1873 163
1874 163
1875 163
1876 163
1877 163

In [14]:
meta_id

{1: measure_point      alvaneu-high_dendrometer_µm_n3_0_1.5_south_psy...
 series_id                                                          1
 series_start                                     2014-05-21 00:00:00
 series_stop                                      2022-10-05 00:00:00
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.48
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                      106.00
 site_temp_ref                                                 1178.0
 Name: 0, Length: 106, dtype: object,
 2: measure_point      alvaneu-high_dendrometer_µm_n4_0_1.5_south_psy...
 series_id                                                          2
 series_start                                     2014-05-21 00:00:00
 series_stop                                      2022-10-05 00:00:00
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.48
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                      106.00
 site_temp_ref                                                 1178.0
 Name: 1, Length: 106, dtype: object,
 3: measure_point      alvaneu-low_dendrometer_µm_n1_0_1.5_south_psyl...
 series_id                                                          3
 series_start                                     2014-05-21 00:00:00
 series_stop                                      2022-10-05 00:00:00
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.51
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                      191.00
 site_temp_ref                                                 1178.0
 Name: 2, Length: 106, dtype: object,
 4: measure_point      alvaneu-low_dendrometer_µm_n2_0_1.5_south_psyl...
 series_id                                                          4
 series_start                                     2014-05-21 00:00:00
 series_stop                                      2022-10-05 00:00:00
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.51
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                      191.00
 site_temp_ref                                                 1178.0
 Name: 3, Length: 106, dtype: object,
 5: measure_point      bachtel-forest_precipitation_mm_meteo_-999_2_b...
 series_id                                                          5
 series_start                                     2012-08-24 00:00:00
 series_stop                                      2022-09-28 00:00:00
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 4, Length: 106, dtype: object,
 6: measure_point      bachtel-forest_rad_w⋅m⁻²_meteo_-999_2_below-ca...
 series_id                                                          6
 series_start                                     2012-09-03 00:00:00
 series_stop                                      2022-09-28 00:00:00
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 5, Length: 106, dtype: object,
 7: measure_point      bachtel-forest_relh_%_buche-4_-999_1.5_below-c...
 series_id                                                          7
 series_start                                     2022-10-06 00:00:00
 series_stop                                                      NaT
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 6, Length: 106, dtype: object,
 8: measure_point      bachtel-forest_relh_%_meteo_-999_2_below-canop...
 series_id                                                          8
 series_start                                     2012-08-24 00:00:00
 series_stop                                      2022-09-28 00:00:00
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 7, Length: 106, dtype: object,
 9: measure_point      bachtel-forest_temp_°c_buche-4_-999_1.5_below-...
 series_id                                                          9
 series_start                                     2022-10-06 00:00:00
 series_stop                                                      NaT
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 8, Length: 106, dtype: object,
 10: measure_point      bachtel-forest_temp_°c_meteo_-999_2_below-cano...
 series_id                                                         10
 series_start                                     2012-08-28 00:00:00
 series_stop                                      2022-09-28 00:00:00
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 9, Length: 106, dtype: object,
 11: measure_point      bachtel-forest_wind_speed_m⋅s⁻¹_meteo_-999_2_b...
 series_id                                                         11
 series_start                                     2012-08-24 00:00:00
 series_stop                                      2022-09-28 00:00:00
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 10, Length: 106, dtype: object,
 12: measure_point      bachtel-forest_soil_temp_°c_buche_-999_-0.1_so...
 series_id                                                         12
 series_start                                     2012-08-28 00:00:00
 series_stop                                                      NaT
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 11, Length: 106, dtype: object,
 13: measure_point      bachtel-forest_soil_temp_°c_buche_-999_-0.3_so...
 series_id                                                         13
 series_start                                     2023-04-06 00:00:00
 series_stop                                                      NaT
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 12, Length: 106, dtype: object,
 14: measure_point      bachtel-forest_soil_temp_°c_fichte-23_1.5_-0.1...
 series_id                                                         14
 series_start                                     2012-09-05 00:00:00
 series_stop                                      2022-08-04 00:00:00
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 13, Length: 106, dtype: object,
 15: measure_point      bachtel-forest_soil_wp_kpa_buche_-999_-0.1_soi...
 series_id                                                         15
 series_start                                     2012-08-28 00:00:00
 series_stop                                                      NaT
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 14, Length: 106, dtype: object,
 16: measure_point      bachtel-forest_soil_wp_kpa_buche_-999_-0.3_soi...
 series_id                                                         16
 series_start                                     2023-04-06 00:00:00
 series_stop                                                      NaT
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 15, Length: 106, dtype: object,
 17: measure_point      bachtel-forest_soil_wp_kpa_fichte-23_1.5_-0.1_...
 series_id                                                         17
 series_start                                     2012-09-03 00:00:00
 series_stop                                      2022-08-04 00:00:00
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 16, Length: 106, dtype: object,
 18: measure_point      bachtel-forest_dendrometer_µm_buche-27_0_1.5_w...
 series_id                                                         18
 series_start                                     2014-12-31 00:00:00
 series_stop                                                      NaT
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 17, Length: 106, dtype: object,
 19: measure_point      bachtel-forest_dendrometer_µm_buche-3_0_1.5_we...
 series_id                                                         19
 series_start                                     2012-08-24 00:00:00
 series_stop                                                      NaT
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 18, Length: 106, dtype: object,
 20: measure_point      bachtel-forest_dendrometer_µm_buche-4_0_1.5_we...
 series_id                                                         20
 series_start                                     2012-08-24 00:00:00
 series_stop                                                      NaT
 series_cutout                    24.11.2021 13:00 - 03.02.2022 11:30
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 19, Length: 106, dtype: object,
 21: measure_point      bachtel-forest_dendrometer_µm_fichte-6_0_1.5_w...
 series_id                                                         21
 series_start                                     2012-08-24 00:00:00
 series_stop                                                      NaT
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 20, Length: 106, dtype: object,
 22: measure_point      bachtel-forest_dendrometer_µm_fichte-60_0_1.5_...
 series_id                                                         22
 series_start                                     2021-05-20 00:00:00
 series_stop                                                      NaT
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 21, Length: 106, dtype: object,
 23: measure_point      bachtel-forest_dendrometer_µm_fichte-7_0_1.5_w...
 series_id                                                         23
 series_start                                     2012-08-24 00:00:00
 series_stop                                                      NaT
 series_cutout                    28.12.2021 01:00 - 03.02.2022 11:30
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 22, Length: 106, dtype: object,
 24: measure_point      bachtel-forest_dendrometer_µm_fichte-8_0_1.5_w...
 series_id                                                         24
 series_start                                     2012-08-24 00:00:00
 series_stop                                      2021-02-03 00:00:00
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.50
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                        None
 site_temp_ref                                                    9.0
 Name: 23, Length: 106, dtype: object,
 25: measure_point      beatenberg-forest_relh_%_baum-5039_-999_2_belo...
 series_id                                                         25
 series_start                                     2019-10-19 00:00:00
 series_stop                                                      NaT
 series_cutout                                                   None
                                          ...
 site_growth_vpd                                                 0.41
 site_n_depo                                                     None
 site_ozon                                                       None
 site_nfk                                                      153.00
 site_temp_ref                                                   26.0
 Name: 24, Length: 106, dtype: object,
 26: measure_point      beatenberg-forest_temp_°c_baum-5039_-999_2_bel...
 series_id                                                         26
 series_start                                     2019-10-19 00:00:00
 series_stop                                                      NaT

In [4]:
dendro

{1:         series_id                  ts        value
 0               1 2014-05-21 12:40:00  2249.375700
 1               1 2014-05-21 12:50:00  2248.375100
 2               1 2014-05-21 13:00:00  2245.998500
 3               1 2014-05-21 13:10:00  2243.332800
 4               1 2014-05-21 13:20:00  2242.045700
 ...           ...                 ...          ...
 438930          1 2022-10-05 00:10:00  4969.418799
 438931          1 2022-10-05 00:20:00  4969.418799
 438932          1 2022-10-05 00:30:00  4969.418799
 438933          1 2022-10-05 00:40:00  4969.418799
 438934          1 2022-10-05 00:50:00  4969.418799

 [438935 rows x 3 columns],
 2:         series_id                  ts        value
 0               2 2014-05-21 13:10:00  3054.553158
 1               2 2014-05-21 13:20:00  3053.101185
 2               2 2014-05-21 13:30:00  3051.026983
 3               2 2014-05-21 13:40:00  3050.171564
 4               2 2014-05-21 13:50:00  3048.342776
 ...           ...                 ...          ...
 438929          2 2022-10-05 00:10:00  6455.667114
 438930          2 2022-10-05 00:20:00  6456.276486
 438931          2 2022-10-05 00:30:00  6456.298828
 438932          2 2022-10-05 00:40:00  6456.886800
 438933          2 2022-10-05 00:50:00  6456.909180

 [438934 rows x 3 columns],
 3:         series_id                  ts        value
 0               3 2014-05-21 12:40:00     2.516805
 1               3 2014-05-21 12:50:00    -0.532220
 2               3 2014-05-21 13:00:00    -3.092387
 3               3 2014-05-21 13:10:00    -5.176333
 4               3 2014-05-21 13:20:00    -6.878067
 ...           ...                 ...          ...
 431458          3 2022-10-05 00:10:00  7365.795627
 431459          3 2022-10-05 00:20:00  7365.795627
 431460          3 2022-10-05 00:30:00  7365.795627
 431461          3 2022-10-05 00:40:00  7365.795627
 431462          3 2022-10-05 00:50:00  7365.795627

 [431463 rows x 3 columns],
 4:         series_id                  ts         value
 0               4 2014-05-21 12:40:00   3772.214407
 1               4 2014-05-21 12:50:00   3768.554000
 2               4 2014-05-21 13:00:00   3765.468070
 3               4 2014-05-21 13:10:00   3762.413673
 4               4 2014-05-21 13:20:00   3759.363333
 ...           ...                 ...           ...
 435216          4 2022-10-05 00:10:00  11582.641602
 435217          4 2022-10-05 00:20:00  11582.641602
 435218          4 2022-10-05 00:30:00  11582.641602
 435219          4 2022-10-05 00:40:00  11582.641602
 435220          4 2022-10-05 00:50:00  11582.641602

 [435221 rows x 3 columns],
 5: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 6: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 7: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 8: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 9: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 10: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 11: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 12: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 13: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 14: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 15: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 16: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 17: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 18:         series_id                  ts         value
 0              18 2014-12-30 00:10:00     18.709339
 1              18 2014-12-30 00:20:00     18.324640
 2              18 2014-12-30 00:30:00     18.740434
 3              18 2014-12-30 00:40:00     18.149665
 4              18 2014-12-30 00:50:00     19.032270
 ...           ...                 ...           ...
 389293         18 2024-03-29 00:00:00  25225.838581
 389294         18 2024-03-29 00:10:00  25225.812196
 389295         18 2024-03-29 00:20:00  25225.771175
 389296         18 2024-03-29 00:30:00  25225.632917
 389297         18 2024-03-29 00:40:00  25225.532698

 [389298 rows x 3 columns],
 19:         series_id                  ts         value
 0              19 2012-08-29 07:50:00    895.880000
 1              19 2012-08-29 08:00:00    895.421796
 2              19 2012-08-29 08:10:00    893.850000
 3              19 2012-08-29 08:20:00    893.850000
 4              19 2012-08-29 08:30:00    893.543333
 ...           ...                 ...           ...
 542851         19 2024-03-29 00:10:00  19475.666686
 542852         19 2024-03-29 00:20:00  19475.644439
 542853         19 2024-03-29 00:30:00  19475.583169
 542854         19 2024-03-29 00:40:00  19475.598213
 542855         19 2024-03-29 00:50:00  19475.599555

 [542856 rows x 3 columns],
 20:         series_id                  ts        value
 0              20 2012-08-29 07:50:00  1040.260000
 1              20 2012-08-29 08:00:00  1040.109654
 2              20 2012-08-29 08:10:00  1040.331392
 3              20 2012-08-29 08:20:00  1039.871805
 4              20 2012-08-29 08:30:00  1039.877047
 ...           ...                 ...          ...
 465634         20 2024-03-29 00:10:00  9688.467977
 465635         20 2024-03-29 00:20:00  9688.479248
 465636         20 2024-03-29 00:30:00  9688.498634
 465637         20 2024-03-29 00:40:00  9688.457222
 465638         20 2024-03-29 00:50:00  9688.414554

 [465639 rows x 3 columns],
 21:         series_id                  ts         value
 0              21 2012-08-29 07:50:00   2100.396055
 1              21 2012-08-29 08:00:00   2099.138166
 2              21 2012-08-29 08:10:00   2098.319825
 3              21 2012-08-29 08:20:00   2097.880299
 4              21 2012-08-29 08:30:00   2097.565263
 ...           ...                 ...           ...
 454484         21 2024-03-29 00:10:00  29215.806142
 454485         21 2024-03-29 00:20:00  29215.655720
 454486         21 2024-03-29 00:30:00  29215.322341
 454487         21 2024-03-29 00:40:00  29214.798966
 454488         21 2024-03-29 00:50:00  29214.717064

 [454489 rows x 3 columns],
 22:         series_id                  ts         value
 0              22 2021-05-20 00:10:00   6191.679186
 1              22 2021-05-20 00:20:00   6188.443190
 2              22 2021-05-20 00:30:00   6185.207195
 3              22 2021-05-20 00:40:00   6181.971199
 4              22 2021-05-20 00:50:00   6178.735204
 ...           ...                 ...           ...
 149799         22 2024-03-29 00:10:00  11086.072803
 149800         22 2024-03-29 00:20:00  11086.053646
 149801         22 2024-03-29 00:30:00  11086.006311
 149802         22 2024-03-29 00:40:00  11085.864580
 149803         22 2024-03-29 00:50:00  11085.637173

 [149804 rows x 3 columns],
 23:         series_id                  ts         value
 0              23 2012-08-29 07:50:00   2841.802256
 1              23 2012-08-29 08:00:00   2841.946617
 2              23 2012-08-29 08:10:00   2841.790850
 3              23 2012-08-29 08:20:00   2841.190000
 4              23 2012-08-29 08:30:00   2839.335338
 ...           ...                 ...           ...
 507822         23 2024-03-29 00:10:00  44168.386525
 507823         23 2024-03-29 00:20:00  44168.486913
 507824         23 2024-03-29 00:30:00  44168.298610
 507825         23 2024-03-29 00:40:00  44168.323074
 507826         23 2024-03-29 00:50:00  44168.228367

 [507827 rows x 3 columns],
 24:         series_id                  ts         value
 0              24 2012-09-05 09:10:00    961.194185
 1              24 2012-09-05 09:20:00    961.715552
 2              24 2012-09-05 09:30:00    962.236920
 3              24 2012-09-05 09:40:00    962.758287
 4              24 2012-09-05 09:50:00    962.768644
 ...           ...                 ...           ...
 352054         24 2021-02-03 00:10:00  16692.591904
 352055         24 2021-02-03 00:20:00  16692.563655
 352056         24 2021-02-03 00:30:00  16692.554152
 352057         24 2021-02-03 00:40:00  16692.589938
 352058         24 2021-02-03 00:50:00  16692.596164

 [352059 rows x 3 columns],
 25: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 26: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 27:         series_id                  ts         value
 0              27 2012-06-20 15:00:00    399.900627
 1              27 2012-06-20 15:10:00    399.937864
 2              27 2012-06-20 15:20:00    399.937864
 3              27 2012-06-20 15:30:00    399.937864
 4              27 2012-06-20 15:40:00    400.476362
 ...           ...                 ...           ...
 584715         27 2024-03-29 15:30:00  12613.960923
 584716         27 2024-03-29 15:40:00  12613.025239
 584717         27 2024-03-29 15:50:00  12612.464680
 584718         27 2024-03-29 16:00:00  12611.734008
 584719         27 2024-03-29 16:10:00  12611.588328

 [584720 rows x 3 columns],
 28:         series_id                  ts        value
 0              28 2012-06-20 15:00:00   291.732155
 1              28 2012-06-20 15:10:00   301.150912
 2              28 2012-06-20 15:20:00   299.478504
 3              28 2012-06-20 15:30:00   301.820716
 4              28 2012-06-20 15:40:00   301.019417
 ...           ...                 ...          ...
 590128         28 2024-03-29 15:20:00  4473.081756
 590129         28 2024-03-29 15:30:00  4473.324953
 590130         28 2024-03-29 15:40:00  4473.380705
 590131         28 2024-03-29 15:50:00  4473.723039
 590132         28 2024-03-29 16:00:00  4473.810391

 [590133 rows x 3 columns],
 29:         series_id                  ts        value
 0              29 2012-06-20 14:50:00   150.916062
 1              29 2012-06-20 15:00:00   151.727321
 2              29 2012-06-20 15:10:00   138.382493
 3              29 2012-06-20 15:20:00   133.131830
 4              29 2012-06-20 15:30:00   132.092857
 ...           ...                 ...          ...
 590232         29 2024-03-29 15:20:00  7984.017196
 590233         29 2024-03-29 15:30:00  7983.904596
 590234         29 2024-03-29 15:40:00  7985.952992
 590235         29 2024-03-29 15:50:00  7981.997677
 590236         29 2024-03-29 16:00:00  7980.401306

 [590237 rows x 3 columns],
 30:         series_id                  ts         value
 0              30 2012-06-20 15:10:00    800.000000
 1              30 2012-06-20 15:20:00    799.656080
 2              30 2012-06-20 15:30:00    799.063530
 3              30 2012-06-20 15:40:00    796.820450
 4              30 2012-06-20 15:50:00    795.756610
 ...           ...                 ...           ...
 590048         30 2024-03-29 15:30:00  33644.230932
 590049         30 2024-03-29 15:40:00  33645.896851
 590050         30 2024-03-29 15:50:00  33646.624490
 590051         30 2024-03-29 16:00:00  33646.692871
 590052         30 2024-03-29 16:10:00  33646.790879

 [590053 rows x 3 columns],
 31:         series_id                  ts         value
 0              31 2012-06-20 14:50:00    478.930829
 1              31 2012-06-20 15:00:00    478.930829
 2              31 2012-06-20 15:10:00    478.930829
 3              31 2012-06-20 15:20:00    478.930829
 4              31 2012-06-20 15:30:00    478.930829
 ...           ...                 ...           ...
 589949         31 2024-03-29 15:30:00  14331.129387
 589950         31 2024-03-29 15:40:00  14330.411280
 589951         31 2024-03-29 15:50:00  14329.492570
 589952         31 2024-03-29 16:00:00  14328.778173
 589953         31 2024-03-29 16:10:00  14328.523388

 [589954 rows x 3 columns],
 32:         series_id                  ts         value
 0              32 2012-06-20 15:10:00    127.133860
 1              32 2012-06-20 15:20:00    126.572507
 2              32 2012-06-20 15:30:00    128.415928
 3              32 2012-06-20 15:40:00    128.704446
 4              32 2012-06-20 15:50:00    128.935399
 ...           ...                 ...           ...
 585170         32 2024-03-29 15:30:00  39164.572514
 585171         32 2024-03-29 15:40:00  39163.641510
 585172         32 2024-03-29 15:50:00  39163.349696
 585173         32 2024-03-29 16:00:00  39161.993046
 585174         32 2024-03-29 16:10:00  39161.603374

 [585175 rows x 3 columns],
 33: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 34: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 35: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 36: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 37: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 38: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 39: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 40: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 41: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 42: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 43: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 44: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 45: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 46: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 47: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 48: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 49: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 50: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 51: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 52: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 53:        series_id                  ts        value
 0             53 2023-03-22 01:10:00  3869.780489
 1             53 2023-03-22 01:20:00  3869.788647
 2             53 2023-03-22 01:30:00  3869.779395
 3             53 2023-03-22 01:40:00  3869.782293
 4             53 2023-03-22 01:50:00  3869.778339
 ...          ...                 ...          ...
 54091         53 2024-04-01 00:10:00  9197.253489
 54092         53 2024-04-01 00:20:00  9197.239148
 54093         53 2024-04-01 00:30:00  9197.223880
 54094         53 2024-04-01 00:40:00  9197.208179
 54095         53 2024-04-01 00:50:00  9197.191131

 [54096 rows x 3 columns],
 54:        series_id                  ts         value
 0             54 2023-03-22 01:10:00   8190.418129
 1             54 2023-03-22 01:20:00   8190.427122
 2             54 2023-03-22 01:30:00   8190.451810
 3             54 2023-03-22 01:40:00   8190.470471
 4             54 2023-03-22 01:50:00   8190.458352
 ...          ...                 ...           ...
 54090         54 2024-04-01 00:10:00  10268.937907
 54091         54 2024-04-01 00:20:00  10268.973255
 54092         54 2024-04-01 00:30:00  10269.002192
 54093         54 2024-04-01 00:40:00  10269.013251
 54094         54 2024-04-01 00:50:00  10269.031102

 [54095 rows x 3 columns],
 55: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 56: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 57: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 58: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 59: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 60: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 61: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 62: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 63: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 64: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 65: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 66: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 67: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 68: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 69: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 70: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 71: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 72:         series_id                  ts         value
 0              72 2018-06-04 11:10:00   9931.431492
 1              72 2018-06-04 11:20:00   9923.953345
 2              72 2018-06-04 11:30:00   9920.954609
 3              72 2018-06-04 11:40:00   9920.015717
 4              72 2018-06-04 11:50:00   9919.525814
 ...           ...                 ...           ...
 240579         72 2024-04-01 00:10:00  27163.829132
 240580         72 2024-04-01 00:20:00  27163.840345
 240581         72 2024-04-01 00:30:00  27163.849338
 240582         72 2024-04-01 00:40:00  27163.882760
 240583         72 2024-04-01 00:50:00  27163.929485

 [240584 rows x 3 columns],
 73:         series_id                  ts        value
 0              73 2014-09-08 15:10:00   -81.610000
 1              73 2014-09-08 15:20:00   -82.527798
 2              73 2014-09-08 15:30:00   -83.870917
 3              73 2014-09-08 15:40:00   -85.214037
 4              73 2014-09-08 15:50:00   -84.685417
 ...           ...                 ...          ...
 312186         73 2021-01-11 12:50:00  9037.449707
 312187         73 2021-01-11 13:00:00  9037.449707
 312188         73 2021-01-11 13:10:00  9037.449707
 312189         73 2021-01-11 13:20:00  9037.449707
 312190         73 2021-01-11 13:30:00  9037.449707

 [312191 rows x 3 columns],
 74:         series_id                  ts         value
 0              74 2018-06-04 11:00:00   5322.581460
 1              74 2018-06-04 11:10:00   5318.118310
 2              74 2018-06-04 11:20:00   5314.345765
 3              74 2018-06-04 11:30:00   5310.618663
 4              74 2018-06-04 11:40:00   5305.125622
 ...           ...                 ...           ...
 230931         74 2024-04-01 00:10:00  37456.644807
 230932         74 2024-04-01 00:20:00  37456.663859
 230933         74 2024-04-01 00:30:00  37456.929064
 230934         74 2024-04-01 00:40:00  37457.088066
 230935         74 2024-04-01 00:50:00  37457.112232

 [230936 rows x 3 columns],
 75:         series_id                  ts         value
 0              75 2014-09-10 01:10:00    125.915383
 1              75 2014-09-10 01:20:00    128.355383
 2              75 2014-09-10 01:30:00    130.376517
 3              75 2014-09-10 01:40:00    132.213383
 4              75 2014-09-10 01:50:00    134.465383
 ...           ...                 ...           ...
 355181         75 2022-06-09 03:20:00  18088.455620
 355182         75 2022-06-09 03:30:00  18088.687132
 355183         75 2022-06-09 03:40:00  18088.687132
 355184         75 2022-06-09 03:50:00  18088.687132
 355185         75 2022-06-09 04:00:00  18088.687132

 [355186 rows x 3 columns],
 76: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 77: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 78: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 79: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 80: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 81: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 82: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 83:        series_id                  ts         value
 0             83 2023-03-22 01:10:00  10297.067397
 1             83 2023-03-22 01:20:00  10297.006307
 2             83 2023-03-22 01:30:00  10297.011544
 3             83 2023-03-22 01:40:00  10297.040780
 4             83 2023-03-22 01:50:00  10297.067460
 ...          ...                 ...           ...
 54088         83 2024-04-01 00:10:00  11491.289139
 54089         83 2024-04-01 00:20:00  11491.290025
 54090         83 2024-04-01 00:30:00  11491.291523
 54091         83 2024-04-01 00:40:00  11491.306680
 54092         83 2024-04-01 00:50:00  11491.345443

 [54093 rows x 3 columns],
 84:        series_id                  ts         value
 0             84 2023-03-22 01:10:00   6772.980504
 1             84 2023-03-22 01:20:00   6772.830025

In [6]:
dendro[3]

        series_id                  ts        value
0               3 2014-05-21 12:40:00     2.516805
1               3 2014-05-21 12:50:00    -0.532220
2               3 2014-05-21 13:00:00    -3.092387
3               3 2014-05-21 13:10:00    -5.176333
4               3 2014-05-21 13:20:00    -6.878067
...           ...                 ...          ...
431458          3 2022-10-05 00:10:00  7365.795627
431459          3 2022-10-05 00:20:00  7365.795627
431460          3 2022-10-05 00:30:00  7365.795627
431461          3 2022-10-05 00:40:00  7365.795627
431462          3 2022-10-05 00:50:00  7365.795627

[431463 rows x 3 columns]

In [16]:
meta_id[2].site_id

1

In [21]:
i=3
a = pd.merge(dendro[i], clima[i], on = "ts", how = "outer")  
a

,series_id,ts,value,site_id,temp,rh,swp,total_precip,rad,vpd,vpd_bo
0,NaN,2010-12-31 23:00:00,NaN,3.0,None,None,None,0.000000,None,None,None
1,NaN,2011-01-01 00:00:00,NaN,3.0,-0.931951,98.937920,None,0.000000,None,0.006088,None
2,NaN,2011-01-01 01:00:00,NaN,3.0,-1.172157,97.857244,None,0.000000,0.000000,0.012069,None
3,NaN,2011-01-01 02:00:00,NaN,3.0,-1.704730,98.901543,None,0.000000,0.000000,0.005949,None
4,NaN,2011-01-01 03:00:00,NaN,3.0,-1.948967,99.245748,None,0.000000,0.000000,0.004012,None
...,...,...,...,...,...,...,...,...,...,...,...
467128,NaN,2023-04-11 10:00:00,NaN,3.0,4.239535,99.997462,-10.316681,None,None,0.000021,None
467129,NaN,2023-04-11 11:00:00,NaN,3.0,3.461016,99.973799,-10.300000,None,None,0.000206,None
467130,NaN,2023-04-11 12:00:00,NaN,3.0,3.374389,100.000000,-10.300000,None,None,0.000000,None
467131,NaN,2023-04-11 13:00:00,NaN,3.0,3.303443,100.000000,-10.300000,None,None,0.000000,None
467132,NaN,2023-04-11 14:00:00,NaN,3.0,3.758560,100.000000,-10.300000,None,None,0.000000,None

In [22]:
b = a [a.value.first_valid_index():a.value.last_valid_index()]
b

,series_id,ts,value,site_id,temp,rh,swp,total_precip,rad,vpd,vpd_bo
29678,3.0,2014-05-21 12:40:00,2.516805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29679,3.0,2014-05-21 12:50:00,-0.532220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29680,3.0,2014-05-21 13:00:00,-3.092387,3.0,23.975927,43.994129,-11.678621,0.000000,746.603170,1.674614,None
29681,3.0,2014-05-21 13:10:00,-5.176333,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29682,3.0,2014-05-21 13:20:00,-6.878067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
462627,3.0,2022-10-05 00:00:00,7365.795627,3.0,None,None,None,0.000000,0.000000,None,None
462628,3.0,2022-10-05 00:10:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
462629,3.0,2022-10-05 00:20:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
462630,3.0,2022-10-05 00:30:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
462631,3.0,2022-10-05 00:40:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
c = b[["series_id", "ts", "value", "temp", "rh", "swp", "total_precip", "rad", "vpd"]].rename(columns={"value": "stem_radius"})
c

,series_id,ts,stem_radius,temp,rh,swp,total_precip,rad,vpd
29678,3.0,2014-05-21 12:40:00,2.516805,NaN,NaN,NaN,NaN,NaN,NaN
29679,3.0,2014-05-21 12:50:00,-0.532220,NaN,NaN,NaN,NaN,NaN,NaN
29680,3.0,2014-05-21 13:00:00,-3.092387,23.975927,43.994129,-11.678621,0.000000,746.603170,1.674614
29681,3.0,2014-05-21 13:10:00,-5.176333,NaN,NaN,NaN,NaN,NaN,NaN
29682,3.0,2014-05-21 13:20:00,-6.878067,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
462627,3.0,2022-10-05 00:00:00,7365.795627,None,None,None,0.000000,0.000000,None
462628,3.0,2022-10-05 00:10:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN
462629,3.0,2022-10-05 00:20:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN
462630,3.0,2022-10-05 00:30:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN
462631,3.0,2022-10-05 00:40:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
start = c.ts.iloc[0]
end = c.ts.iloc[-1]
complete_times = {'ts': pd.date_range(start=start, end=end, freq='10Min')}

In [24]:
d = pd.merge(c, pd.DataFrame(complete_times), on = "ts", how = "outer")
d

,series_id,ts,stem_radius,temp,rh,swp,total_precip,rad,vpd
0,3.0,2014-05-21 12:40:00,2.516805,NaN,NaN,NaN,NaN,NaN,NaN
1,3.0,2014-05-21 12:50:00,-0.532220,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,2014-05-21 13:00:00,-3.092387,23.975927,43.994129,-11.678621,0.000000,746.603170,1.674614
3,3.0,2014-05-21 13:10:00,-5.176333,NaN,NaN,NaN,NaN,NaN,NaN
4,3.0,2014-05-21 13:20:00,-6.878067,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
440420,3.0,2022-10-05 00:00:00,7365.795627,None,None,None,0.000000,0.000000,None
440421,3.0,2022-10-05 00:10:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN
440422,3.0,2022-10-05 00:20:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN
440423,3.0,2022-10-05 00:30:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN
440424,3.0,2022-10-05 00:40:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df[int(d.iloc[0].series_id)]

NameError: name 'df' is not defined