In [ ]:
import pandas as pd
import sys
import numpy as np
sys.path.insert(0, '../raw_data_elaboration/tools/')

import data_processing_library as dpl

2025-04-16 10:45:27.606028: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1744793127.622832  120004 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1744793127.628027  120004 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-04-16 10:45:27.645387: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [ ]:
meta = dpl.load_dataframe("/storage/lukovic/Data/FORWARDS/treenet/server_data/metadata_dendrometer.pkl")
dendro = dpl.load_dataframe("/storage/lukovic/Data/FORWARDS/treenet/server_data/data_dendro_lm.pkl")
clima = dpl.load_dataframe("/storage/lukovic/Data/FORWARDS/treenet/server_data/data_meteo_l2.pkl")

In [17]:
meta = dpl.load_dataframe("/storage/lukovic/Data/FORWARDS/treenet/server_data/metadata_all.pkl")

In [16]:
import pickle
with open("metadata_dendrometer.pkl", 'wb') as f:
        pickle.dump(new_meta, f)

In [49]:
meta_id = {}
for index, row in meta.iterrows():    
    print(row.series_id, row.site_id)
    meta_id[row.series_id] = row

1 1
2 1
3 2
4 2
5 3
6 3
7 3
8 3
9 3
10 3
11 3
12 3
13 3
14 3
15 3
16 3
17 3
18 3
19 3
20 3
21 3
22 3
23 3
24 3
25 4
26 4
27 4
28 4
29 4
30 4
31 4
32 4
33 4
34 4
35 5
36 5
37 5
38 6
39 6
40 6
41 6
42 7
43 7
44 7
45 8
46 8
47 8
48 9
49 9
50 9
51 10
52 10
53 10
54 10
55 10
56 10
57 10
58 10
59 10
60 10
61 10
62 10
63 10
64 10
65 10
66 10
67 10
68 10
69 10
70 10
71 10
72 10
73 10
74 10
75 10
76 10
77 10
78 10
79 10
80 10
81 10
82 10
83 10
84 10
85 10
86 11
87 11
88 11
89 11
90 12
91 12
92 12
93 13
94 13
95 14
96 14
97 14
98 15
99 15
100 15
101 16
102 16
103 16
104 17
105 17
106 17
107 18
108 18
109 19
110 19
111 19
112 20
113 20
114 20
115 21
116 21
117 21
118 22
119 22
120 22
121 22
122 23
123 23
124 23
125 23
126 23
127 23
128 23
129 134
130 23
131 23
132 23
133 23
134 134
135 23
136 23
137 23
138 23
139 23
140 24
141 24
142 24
144 25
145 25
147 26
148 26
149 26
150 27
151 27
152 27
153 28
154 28
155 28
156 29
157 29
158 30
159 30
160 30
161 30
162 31
163 31
164 32
165 32
166 32
167 32
168 32
169 32
170 33
171 33
172 33
173 33
174 34
175 34
176 34
177 34
178 34
179 34
180 34
181 34
182 34
183 34
184 34
185 34
186 34
187 34
188 34
189 34
190 34
191 34
192 34
193 34
194 34
195 34
196 35
197 35
198 35
199 35
200 35
201 35
202 35
203 35
204 35
205 35
206 35
207 35
208 35
209 36
210 36
211 36
212 36
213 36
214 36
215 36
216 36
217 36
218 36
219 36
220 36
221 36
222 36
223 36
224 36
225 36
226 36
227 36
228 36
229 36
230 36
231 36
232 36
233 36
234 36
235 36
236 36
237 36
238 36
239 36
240 36
241 36
242 36
243 36
244 36
245 36
246 36
247 36
248 36
249 36
250 36
251 36
252 36
253 36
254 36
255 36
256 36
257 36
258 36
259 36
260 36
261 36
262 36
263 36
264 36
265 36
266 36
267 36
268 36
269 36
270 36
271 36
272 36
273 36
274 36
275 36
276 36
277 36
278 36
279 36
280 36
281 36
282 36
283 36
284 36
285 36
286 36
287 36
288 36
289 36
290 36
291 36
292 36
293 36
294 36
295 36
296 36
297 36
298 36
299 36
300 36
301 36
302 36
303 36
304 36
305 36
306 36
307 36
308 36
309 36
310 36
311 36
312 36
313 36
314 36
315 36
316 36
317 36
318 36
319 36
320 36
321 36
322 36
323 36
324 36
325 36
326 36
327 36
328 36
329 36
330 36
331 36
332 36
333 36
334 36
335 36
336 36
337 36
338 36
339 36
340 36
341 36
342 36
343 36
344 36
345 36
346 36
347 36
348 36
349 36
350 36
351 36
352 36
353 36
354 36
355 36
356 36
357 36
358 36
359 36
360 36
361 37
362 37
363 37
364 38
365 38
366 38
367 38
368 39
369 39
370 39
371 40
372 40
373 40
374 41
375 41
376 41
377 42
378 42
379 42
380 42
381 42
382 42
383 42
384 42
385 42
386 42
387 42
388 42
389 42
390 42
391 42
392 42
393 42
394 42
395 42
396 42
397 42
398 42
399 43
400 43
401 43
402 43
403 43
404 43
405 43
406 43
407 43
408 43
409 43
410 43
411 43
412 43
413 43
414 43
415 43
416 43
417 43
418 43
419 43
420 44
421 44
422 44
423 44
424 44
425 44
426 44
427 44
428 44
429 44
430 44
431 44
432 44
433 44
434 44
435 44
436 44
437 44
438 44
439 44
440 44
441 44
442 44
443 44
444 44
445 44
446 44
447 44
448 44
449 45
450 45
451 45
452 45
453 45
454 45
455 45
456 45
457 45
458 45
459 45
460 45
461 45
462 45
463 45
464 45
465 45
466 45
467 45
468 45
469 45
470 45
471 45
472 45
473 45
474 45
475 45
476 45
477 45
478 45
479 45
480 45
481 45
482 45
483 45
484 45
485 45
486 45
487 45
488 45
490 45
491 45
492 45
493 45
494 45
495 45
496 45
497 45
498 45
499 45
500 45
501 45
502 45
503 45
504 45
505 45
506 45
507 45
508 45
509 45
510 45
511 45
512 45
513 45
514 45
515 45
516 45
517 45
518 45
519 45
520 45
521 45
522 45
523 45
524 45
525 45
526 45
527 45
528 45
529 45
530 45
531 45
532 45
533 45
534 45
535 45
536 45
537 46
538 46
539 46
540 46
541 46
542 46
543 46
544 46
545 46
546 46
547 46
548 46
549 46
550 46
551 46
552 46
553 46
554 46
555 47
556 47
557 47
558 47
559 48
560 48
561 48
562 48
563 48
564 48
565 48
566 48
567 48
568 48
569 48
570 49
571 49
572 49
573 49
574 49
575 49
576 49
577 49
578 49
579 49
580 50
581 50
582 50
583 50
584 50
585 50
586 50
587 50
588 50
589 50
590 50
591 50
592 50
593 50
594 50
595 50
596 50
597 50
598 50
599 50
600 50
601 50
602 50
603 50
604 50
605 51
606 51
607 51
608 51
609 51
610 51
611 51
612 51
613 51
614 51
615 51
616 51
617 51
618 51
619 51
620 51
621 51
622 51
623 51
624 51
625 51
626 51
627 51
628 51
629 51
630 51
631 51
632 51
633 51
634 51
635 51
636 51
637 51
638 51
639 51
640 51
641 51
642 51
643 51
644 51
645 51
646 51
647 51
648 51
649 51
650 51
651 51
652 51
653 51
654 51
655 51
656 51
657 51
658 51
659 51
660 51
661 51
662 51
663 51
664 51
665 51
666 51
667 51
668 51
669 51
670 51
671 51
672 51
673 51
674 51
675 51
676 51
677 51
678 51
679 51
680 51
681 51
682 51
683 51
684 51
685 51
686 52
687 52
688 52
689 52
690 52
691 52
692 52
693 52
694 52
695 52
696 53
697 53
698 53
699 53
700 54
701 54
702 54
703 54
704 54
705 54
706 54
707 54
708 54
709 54
710 54
711 54
712 55
713 55
714 55
715 55
716 56
717 56
718 57
719 57
720 57
721 57
722 57
723 57
724 57
725 57
726 57
727 57
728 57
729 57
730 58
731 58
732 58
733 58
734 58
735 58
736 59
737 59
738 60
739 60
740 60
741 60
742 60
743 60
744 60
745 60
746 60
747 60
748 60
749 60
750 61
751 61
752 61
753 61
754 61
755 61
756 62
757 62
758 62
759 62
760 62
761 62
762 62
763 62
764 62
765 62
766 62
767 62
768 63
769 63
770 64
771 64
772 64
773 64
774 64
775 64
776 64
777 64
778 65
779 65
780 65
781 65
782 66
783 66
784 66
785 66
786 66
787 66
788 66
789 66
790 66
791 66
792 66
793 66
794 67
795 67
796 67
797 67
798 67
799 67
800 68
801 68
802 68
803 68
804 68
805 68
806 68
807 68
808 69
809 69
810 69
811 69
812 69
813 69
814 70
815 70
816 70
817 70
818 70
819 70
820 70
821 70
822 70
823 70
824 70
825 70
826 70
827 70
828 70
829 70
830 70
831 70
832 70
833 70
834 70
835 70
836 70
837 70
838 70
839 71
840 71
841 71
842 71
843 71
844 71
845 71
846 71
847 72
848 72
849 72
850 72
851 73
852 73
853 73
854 73
855 74
856 74
857 75
858 75
859 75
860 75
861 75
862 75
863 75
864 75
865 75
866 75
867 75
868 75
869 75
870 75
871 75
872 75
873 75
874 75
875 75
876 75
877 75
878 75
879 75
880 75
881 75
882 75
883 76
884 76
885 76
886 77
887 77
888 78
889 78
890 78
891 79
892 79
893 79
894 80
895 80
896 80
897 81
898 81
899 81
900 82
901 82
902 83
903 83
904 83
905 84
906 84
907 84
908 85
909 85
910 85
911 86
912 86
913 86
914 86
915 86
916 86
917 86
918 86
919 86
920 86
921 86
922 86
923 86
924 86
925 86
926 86
927 86
928 86
929 86
930 86
931 86
932 86
933 86
934 86
935 86
936 86
937 86
938 86
939 86
940 86
941 86
942 86
943 86
944 86
945 86
946 86
947 86
948 86
949 86
950 86
951 86
952 86
953 86
954 86
955 86
956 86
957 86
958 86
959 86
960 86
961 86
962 86
963 86
964 87
965 87
966 87
967 87
968 88
969 88
970 88
971 88
972 89
973 89
974 89
975 89
976 89
977 89
978 89
979 89
980 89
981 89
982 89
983 89
984 89
985 89
986 89
987 89
988 89
989 89
990 89
991 89
992 89
993 89
994 89
995 89
996 89
997 89
998 89
999 89
1000 89
1001 89
1002 89
1003 89
1004 89
1005 89
1006 89
1007 90
1008 90
1009 90
1010 90
1011 90
1012 90
1013 90
1014 90
1015 90
1016 90
1017 90
1018 90
1019 90
1020 90
1021 90
1022 90
1023 90
1024 90
1025 90
1026 90
1027 90
1028 90
1029 90
1030 90
1031 90
1032 90
1033 90
1034 90
1035 90
1036 90
1037 90
1038 90
1039 90
1040 90
1041 90
1042 90
1043 90
1044 90
1045 90
1046 90
1047 90
1048 90
1049 90
1050 91
1051 91
1052 91
1053 91
1054 91
1055 91
1056 91
1057 91
1058 91
1059 91
1060 92
1061 92
1062 92
1063 92
1064 92
1065 92
1066 92
1067 93
1068 93
1069 93
1070 93
1071 93
1072 93
1073 93
1074 93
1075 93
1076 93
1077 94
1078 94
1079 94
1080 94
1081 94
1082 94
1083 95
1084 95
1085 95
1086 95
1087 95
1088 95
1089 95
1090 95
1091 95
1092 96
1093 96
1094 96
1095 96
1096 96
1097 96
1098 96
1099 96
1100 96
1101 96
1102 96
1103 96
1104 96
1105 96
1106 96
1107 96
1108 97
1109 97
1110 97
1111 97
1112 97
1113 97
1114 97
1115 97
1116 97
1117 97
1118 98
1119 98
1120 98
1121 98
1122 98
1123 98
1124 98
1125 98
1126 98
1127 98
1128 98
1129 98
1130 98
1131 98
1132 98
1133 98
1134 98
1135 98
1136 98
1137 98
1138 98
1139 98
1140 98
1141 98
1142 98
1143 98
1144 98
1145 98
1146 98
1147 99
1148 99
1149 99
1150 99
1151 99
1152 99
1153 99
1154 99
1155 99
1156 99
1157 99
1158 99
1159 99
1160 99
1161 99
1162 100
1163 100
1164 100
1165 100
1166 100
1167 101
1168 101
1169 101
1170 101
1171 101
1172 102
1173 102
1174 102
1175 102
1176 102
1177 102
1178 102
1179 102
1180 102
1181 102
1182 102
1183 102
1184 102
1185 102
1186 102
1187 102
1188 102
1189 102
1190 102
1191 102
1192 102
1193 102
1194 102
1195 102
1196 102
1197 102
1198 102
1199 102
1200 102
1201 102
1202 102
1203 102
1204 103
1205 103
1206 103
1207 103
1208 103
1209 103
1210 104
1211 104
1212 105
1213 105
1214 105
1215 105
1216 105
1217 105
1218 105
1219 105
1220 105
1221 105
1222 105
1223 105
1224 105
1225 105
1226 105
1227 105
1228 105
1229 105
1230 106
1231 106
1232 106
1233 106
1234 106
1235 106
1236 106
1237 106
1238 107
1239 107
1240 107
1241 107
1242 107
1243 107
1244 107
1245 107
1246 107
1247 107
1248 107
1249 107
1250 107
1251 107
1252 108
1253 108
1254 108
1255 108
1256 108
1257 108
1258 108
1259 108
1260 108
1261 108
1262 108
1263 108
1264 108
1265 108
1266 109
1267 109
1268 109
1269 109
1270 109
1271 109
1272 109
1273 109
1274 110
1275 110
1276 110
1277 110
1278 110
1279 110
1280 111
1281 111
1282 111
1283 111
1284 111
1285 111
1286 111
1287 111
1288 111
1289 111
1290 111
1291 112
1292 112
1293 112
1294 112
1295 112
1296 112
1297 112
1298 112
1299 112
1300 112
1301 112
1302 113
1303 113
1304 113
1305 113
1306 113
1307 113
1308 113
1309 113
1310 113
1311 113
1312 113
1313 114
1314 114
1315 114
1316 114
1317 115
1318 115
1319 115
1320 115
1321 115
1322 115
1323 115
1324 115
1325 115
1326 115
1327 115
1328 116
1329 116
1330 116
1331 116
1332 116
1333 116
1334 116
1335 116
1336 116
1337 116
1338 116
1339 116
1340 117
1341 117
1342 117
1343 117
1344 117
1345 117
1346 117
1347 117
1348 117
1349 117
1350 117
1351 118
1352 118
1353 118
1354 118
1355 118
1356 118
1357 118
1358 118
1359 118
1360 118
1361 118
1362 118
1363 118
1364 118
1365 119
1366 119
1367 119
1368 119
1369 119
1370 119
1371 119
1372 119
1373 119
1374 119
1375 119
1376 119
1377 119
1378 119
1379 120
1380 120
1381 120
1382 120
1383 120
1384 120
1385 120
1386 120
1387 121
1388 121
1389 121
1390 121
1391 121
1392 121
1393 121
1394 121
1395 121
1396 121
1397 121
1398 121
1399 122
1400 122
1401 122
1402 122
1403 122
1404 122
1405 122
1406 122
1407 122
1408 122
1409 123
1410 123
1411 123
1412 124
1413 124
1414 125
1415 125
1416 125
1417 126
1418 126
1419 126
1420 127
1421 127
1422 127
1423 128
1424 128
1425 128
1427 129
1428 129
1430 130
1431 130
1432 130
1433 131
1434 131
1435 131
1436 132
1437 132
1438 132
1439 133
1440 134
1441 134
1442 134
1443 134
1444 134
1445 134
1446 134
1447 134
1448 134
1449 134
1450 134
1451 134
1452 134
1453 134
1454 134
1455 135
1456 135
1457 135
1458 135
1459 135
1460 135
1461 135
1462 135
1463 135
1464 135
1465 135
1466 136
1467 136
1468 136
1469 136
1470 137
1471 137
1472 137
1473 137
1474 137
1475 137
1476 137
1477 137
1478 137
1479 138
1480 138
1481 138
1482 138
1483 138
1484 138
1485 138
1486 138
1487 138
1488 138
1489 138
1490 139
1491 139
1492 139
1493 139
1494 139
1495 139
1496 139
1497 139
1498 139
1499 139
1500 139
1501 140
1502 140
1503 140
1504 140
1505 140
1506 140
1507 140
1508 140
1509 140
1510 140
1511 140
1512 141
1513 141
1514 141
1515 141
1516 142
1517 142
1518 142
1519 142
1520 142
1521 142
1522 142
1523 142
1524 142
1525 142
1526 142
1527 143
1528 143
1529 143
1530 143
1531 143
1532 143
1533 143
1534 143
1535 143
1536 144
1537 144
1538 144
1539 144
1540 144
1541 144
1542 144
1543 144
1544 144
1545 144
1546 144
1547 86
1548 86
1549 86
1550 86
1551 86
1552 86
1553 86
1554 86
1555 86
1556 90
1557 90
1558 90
1559 90
1560 90
1561 90
1562 90
1563 90
1564 90
1565 145
1566 145
1567 145
1568 145
1569 145
1570 145
1571 145
1572 145
1573 145
1574 146
1575 146
1576 146
1577 146
1578 146
1579 146
1580 146
1581 146
1582 146
1583 147
1584 147
1585 147
1586 147
1587 147
1588 147
1589 147
1590 147
1591 147
1592 95
1593 95
1594 86
1595 86
1596 86
1597 86
1598 105
1599 105
1600 157
1601 157
1602 157
1603 160
1604 160
1605 160
1606 160
1607 160
1608 157
1609 157
1610 157
1611 157
1612 157
1613 157
1614 157
1615 160
1616 160
1617 160
1618 157
1619 157
1620 43
1621 43
1622 43
1623 43
1624 43
1625 43
1626 161
1627 161
1628 162
1629 162
1630 161
1631 161
1632 161
1633 161
1634 161
1635 161
1636 162
1637 162
1638 162
1639 163
1640 163
1641 163
1642 163
1643 163
1644 163
1645 164
1646 164
1647 164
1648 164
1649 164
1650 164
1651 164
1652 164
1653 164
1654 164
1655 164
1656 164
1657 164
1658 164
1659 164
1660 164
1661 165
1662 165
1663 165
1664 165
1665 165
1666 165
1667 165
1668 165
1669 165
1670 165
1671 165
1672 165
1673 165
1674 165
1675 166
1676 166
1677 166
1678 166
1679 166
1680 166
1681 166
1682 166
1683 166
1684 166
1685 166
1686 166
1687 166
1688 166
1689 157
1690 157
1691 157
1692 157
1693 167
1694 167
1695 167
1696 167
1697 167
1698 167
1699 167
1700 167
1701 167
1702 167
1703 167
1704 167
1705 167
1706 167
1707 167
1708 167
1709 160
1710 160
1711 160
1712 160
1713 160
1714 160
1715 160
1716 163
1717 164
1718 165
1719 166
1720 167
1721 160
1722 163
1723 164
1724 165
1725 166
1726 167
1727 146
1728 129
1729 25
1730 25
1731 129
1732 157
1733 157
1734 157
1735 157
1736 157
1737 157
1738 157
1739 157
1740 157
1741 157
1742 157
1743 157
1744 160
1745 160
1746 160
1747 160
1748 160
1749 160
1750 160
1751 160
1752 160
1753 160
1754 160
1755 160
1756 164
1757 164
1758 166
1759 166
1760 166
1761 166
1762 166
1763 166
1764 164
1765 164
1766 164
1767 164
1768 164
1769 164
1770 166
1771 166
1772 166
1773 166
1774 166
1775 166
1776 164
1777 164
1778 164
1779 164
1780 167
1781 167
1782 167
1783 167
1784 167
1785 167
1786 167
1787 167
1788 167
1789 167
1790 167
1791 167
1792 165
1793 165
1794 165
1795 165
1796 165
1797 165
1798 165
1799 165
1800 165
1801 165
1802 165
1803 165
1805 5
1806 10
1807 90
1808 13
1809 14
1810 19
1811 118
1812 118
1813 118
1814 118
1815 118
1816 118
1817 118
1820 134
1821 36
1826 34
1827 34
1828 49
1829 49
1830 101
1831 22
1832 22
1833 22
1834 22
1835 22
1836 22
1837 169
1838 169
1839 169
1840 169
1841 169
1842 169
1843 169
1844 169
1845 170
1846 170
1847 170
1848 170
1849 170
1850 170
1851 170
1852 170
1853 171
1854 171
1855 171
1856 171
1857 171
1858 50
1859 146
1860 44
1866 44
1869 43
1870 44
1871 44
1872 163
1873 163
1874 163
1875 163
1876 163
1877 163

In [11]:
list(meta)

['measure_point',
 'series_id',
 'series_start',
 'series_stop',
 'series_cutout',
 'series_active',
 'series_display',
 'variable_id',
 'variable_name',
 'variable_resolution',
 'variable_units',
 'sensor_id',
 'sensor_name',
 'sensor_class',
 'sensor_data_source',
 'position_id',
 'series_height',
 'series_exposition',
 'series_distance_to_tree',
 'tree_id',
 'tree_name',
 'tree_xcor',
 'tree_ycor',
 'tree_altitude',
 'tree_genus',
 'tree_species',
 'tree_dbh',
 'tree_height',
 'tree_status',
 'tree_age',
 'tree_phloem_thickness_mm',
 'tree_totalbark_thickness_mm',
 'tree_sapwood_thickness_cm',
 'tree_sapwood_area',
 'series_dsri_max',
 'series_dsri_min',
 'series_twd_max_gp',
 'series_twd_med_gp',
 'series_twd_min_gp',
 'series_twd_max_nogp',
 'series_twd_med_nogp',
 'series_twd_min_nogp',
 'series_twd_max_frost',
 'series_twd_med_frost',
 'series_twd_min_frost',
 'series_gro_start_doy_med',
 'series_gro_end_doy_med',
 'series_gro_max_yr',
 'series_gro_med_yr',
 'series_gro_min_yr',
 'series_gro_max_month',
 'series_gro_med_month',
 'series_gro_min_month',
 'series_gro_max_week',
 'series_gro_med_week',
 'series_gro_min_week',
 'series_gro_max_day',
 'series_gro_med_day',
 'series_gro_min_day',
 'series_gro_max_hr',
 'series_gro_med_hr',
 'series_gro_min_hr',
 'series_timing_gro_year_max',
 'series_timing_gro_year_min',
 'series_timing_gro_month_max',
 'series_timing_gro_week_max',
 'series_timing_gro_doy_max',
 'series_timing_gro_hour_max',
 'series_timing_gro_hour_min',
 'series_grohours_med',
 'series_grohours_gp_med',
 'series_grohours_percent_med',
 'series_mds_gp_med',
 'series_mds_gp_max',
 'series_twd_gp_morning',
 'series_proc_tol',
 'series_proc_tol_out',
 'series_proc_tol_jump',
 'series_proc_frost_thr',
 'site_id',
 'site_name',
 'site_subplot',
 'site_exposition',
 'site_xcor',
 'site_ycor',
 'site_altitude',
 'site_forest_type',
 'site_soil_type',
 'site_affiliation',
 'site_area',
 'region',
 'country',
 'site_annual_temp',
 'site_growth_temp',
 'site_annual_precip',
 'site_growth_precip',
 'site_annual_rad',
 'site_growth_rad',
 'site_annual_relh',
 'site_growth_relh',
 'site_annual_vpd',
 'site_growth_vpd',
 'site_n_depo',
 'site_ozon',
 'site_nfk',
 'site_temp_ref']

In [50]:
meta_id[1]

measure_point      alvaneu-high_dendrometer_µm_n3_0_1.5_south_psy...
series_id                                                          1
series_start                                     2014-05-21 00:00:00
series_stop                                      2022-10-05 00:00:00
series_cutout                                                   None
                                         ...
site_growth_vpd                                                 0.48
site_n_depo                                                     None
site_ozon                                                       None
site_nfk                                                      106.00
site_temp_ref                                                 1178.0
Name: 0, Length: 106, dtype: object

In [79]:
for index, row in clima.items():
    print(row)

       site_id                  ts      temp         rh         swp  \
0            1 2011-10-13 09:00:00      None       None        None
1            1 2011-10-13 10:00:00      None       None        None
2            1 2011-10-13 11:00:00      None       None        None
3            1 2011-10-13 12:00:00      None       None        None
4            1 2011-10-13 13:00:00      None       None        None
...        ...                 ...       ...        ...         ...
96234        1 2022-10-05 03:00:00  8.333333  47.833333  -11.336063
96235        1 2022-10-05 04:00:00  8.000000  46.500000  -11.342608
96236        1 2022-10-05 05:00:00  8.166667  45.166667  -11.346543
96237        1 2022-10-05 06:00:00  8.500000  42.666667  -11.346577
96238        1 2022-10-05 07:00:00  9.166667  44.833333  -11.354489

      total_precip         rad       vpd    vpd_bo
0         0.000000        None      None      None
1         0.000000  412.166667      None      None
2         0.000000  352.833333      None      None
3         0.000000  452.333333      None      None
4         0.000000  587.166667      None      None
...            ...         ...       ...       ...
96234     0.000000    1.000000  0.574437  0.575383
96235     0.000000    0.000000  0.575926  0.576168
96236     0.000000    0.000000  0.597006  0.598151
96237     0.000000    7.000000  0.638506  0.638774
96238     0.000000   24.000000  0.642691  0.643800

[96239 rows x 9 columns]
       site_id                  ts      temp         rh         swp  \
0            2 2011-10-13 09:00:00      None       None        None
1            2 2011-10-13 10:00:00      None       None        None
2            2 2011-10-13 11:00:00      None       None        None
3            2 2011-10-13 12:00:00      None       None        None
4            2 2011-10-13 13:00:00      None       None        None
...        ...                 ...       ...        ...         ...
96235        2 2022-10-05 04:00:00  8.333333  45.333333  -11.326052
96236        2 2022-10-05 05:00:00  8.166667  43.500000  -11.328660
96237        2 2022-10-05 06:00:00  8.500000  41.833333  -11.329960
96238        2 2022-10-05 07:00:00  8.666667  39.500000  -11.331269
96239        2 2022-10-05 08:00:00  9.166667  42.500000  -11.333870

      total_precip         rad       vpd    vpd_bo
0         0.000000        None      None      None
1         0.000000  412.166667      None      None
2         0.000000  352.833333      None      None
3         0.000000  452.333333      None      None
4         0.000000  587.166667      None      None
...            ...         ...       ...       ...
96235     0.000000    0.000000  0.601975  0.602865
96236     0.000000    0.000000  0.615162  0.615852
96237     0.000000    7.000000  0.647797  0.648058
96238     0.000000   24.000000  0.681431  0.681974
96239     0.000000  245.000000  0.669885  0.670494

[96240 rows x 9 columns]
        site_id                  ts       temp          rh         swp  \
0             3 2010-12-31 23:00:00       None        None        None
1             3 2011-01-01 00:00:00  -0.931951   98.937920        None
2             3 2011-01-01 01:00:00  -1.172157   97.857244        None
3             3 2011-01-01 02:00:00  -1.704730   98.901543        None
4             3 2011-01-01 03:00:00  -1.948967   99.245748        None
...         ...                 ...        ...         ...         ...
107577        3 2023-04-11 10:00:00   4.239535   99.997462  -10.316681
107578        3 2023-04-11 11:00:00   3.461016   99.973799  -10.300000
107579        3 2023-04-11 12:00:00   3.374389  100.000000  -10.300000
107580        3 2023-04-11 13:00:00   3.303443  100.000000  -10.300000
107581        3 2023-04-11 14:00:00   3.758560  100.000000  -10.300000

       total_precip       rad       vpd vpd_bo
0          0.000000      None      None   None
1          0.000000      None  0.006088   None
2          0.000000  0.000000  0.012069   None
3          0.000000  0.000000  0.005949   None
4          0.000000  0.000000  0.004012   None
...             ...       ...       ...    ...
107577         None      None  0.000021   None
107578         None      None  0.000206   None
107579         None      None  0.000000   None
107580         None      None  0.000000   None
107581         None      None  0.000000   None

[107582 rows x 9 columns]
        site_id                  ts       temp          rh        swp  \
0             4 2010-12-31 23:00:00  -2.783333  100.000000       None
1             4 2011-01-01 00:00:00  -3.016667  100.000000       None
2             4 2011-01-01 01:00:00  -2.633333  100.000000       None
3             4 2011-01-01 02:00:00  -3.166667  100.000000       None
4             4 2011-01-01 03:00:00  -3.083333  100.000000       None
...         ...                 ...        ...         ...        ...
107580        4 2023-04-11 11:00:00   3.188325   94.380865  -8.200000
107581        4 2023-04-11 12:00:00   3.487458   94.516241  -8.200000
107582        4 2023-04-11 13:00:00   3.088166   92.584832  -8.200000
107583        4 2023-04-11 14:00:00   2.836271   94.513652  -8.200000
107584        4 2023-04-11 15:00:00       None        None  -8.200000

       total_precip       rad       vpd vpd_bo
0          0.000000      None  0.000000   None
1          0.000000  0.000000  0.000000   None
2          0.000000  0.000000  0.000000   None
3          0.000000  0.000000  0.000000   None
4          0.000000  0.000000  0.000000   None
...             ...       ...       ...    ...
107580         None      None  0.043320   None
107581         None      None  0.043179   None
107582         None      None  0.056762   None
107583         None      None  0.041254   None
107584         None      None      None   None

[107585 rows x 9 columns]
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
        site_id                  ts       temp         rh   swp total_precip  \
0            10 2010-12-31 23:00:00       None       None  None     0.000000
1            10 2011-01-01 00:00:00   0.139687  97.715482  None     0.000000
2            10 2011-01-01 01:00:00   0.093596  96.944852  None     0.000000
3            10 2011-01-01 02:00:00   0.067998  96.175435  None     0.000000
4            10 2011-01-01 03:00:00   0.169906  95.049778  None     0.000000
...         ...                 ...        ...        ...   ...          ...
107358       10 2023-04-11 11:00:00   9.301199  81.995348  None         None
107359       10 2023-04-11 12:00:00   9.095718  76.482576  None         None
107360       10 2023-04-11 13:00:00   9.280180  75.642006  None         None
107361       10 2023-04-11 14:00:00  10.172811  72.686738  None         None
107362       10 2023-04-11 15:00:00  10.652229  73.506048  None         None

         rad       vpd vpd_bo
0       None      None   None
1       None  0.014162   None
2       None  0.018876   None
3       None  0.023585   None
4       None  0.030754   None
...      ...       ...    ...
107358  None  0.211734   None
107359  None  0.272761   None
107360  None  0.286044   None
107361  None  0.340549   None
107362  None  0.341074   None

[107363 rows x 9 columns]
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
        site_id                  ts       temp         rh   swp total_precip  \
0            22 2010-12-31 23:00:00       None       None  None     0.000000
1            22 2011-01-01 00:00:00       None       None  None     0.000000
2            22 2011-01-01 01:00:00       None       None  None     0.000000
3            22 2011-01-01 02:00:00       None       None  None     0.000000
4            22 2011-01-01 03:00:00       None       None  None     0.000000
...         ...                 ...        ...        ...   ...          ...
107603       22 2023-04-11 10:00:00   7.617433  83.241758  None         None
107604       22 2023-04-11 11:00:00   8.693496  78.270376  None         None
107605       22 2023-04-11 12:00:00   9.374954  76.077618  None         None
107606       22 2023-04-11 13:00:00   9.422733  72.006300  None         None
107607       22 2023-04-11 14:00:00  10.007794  68.118092  None         None

               rad       vpd vpd_bo
0             None      None   None
1         0.000000      None   None
2         0.000000      None   None
3         0.000000      None   None
4         0.000000      None   None
...            ...       ...    ...
107603  431.000000  0.175812   None
107604  393.000000  0.245262   None
107605  299.000000  0.282717   None
107606  298.000000  0.331897   None
107607  280.000000  0.393133   None

[107608 rows x 9 columns]
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
       site_id                  ts       temp         rh         swp  \
0          134 2020-09-10 01:00:00  16.035497  81.204947  -10.500000
1          134 2020-09-10 02:00:00  15.866856  82.176146  -10.500000
2          134 2020-09-10 03:00:00  15.591256  82.431164  -10.588740
3          134 2020-09-10 04:00:00  15.529002  81.363458  -10.630392
4          134 2020-09-10 05:00:00  15.191504  82.941198        None
...        ...                 ...        ...        ...         ...
22610      134 2023-04-11 10:00:00   9.730434  74.302417  -11.000000
22611      134 2023-04-11 11:00:00  10.566490  65.296535  -11.000000
22612      134 2023-04-11 12:00:00       None       None  -11.000000
22613      134 2023-04-11 13:00:00  10.524158  63.963945  -11.000000
22614      134 2023-04-11 14:00:00  11.969167  56.036334  -11.000000

      total_precip   rad       vpd vpd_bo
0         0.000000  None  0.343746   None
1         0.000000  None  0.322490   None
2         0.000000  None  0.312318   None
3         0.000000  None  0.329979   None
4         0.000000  None  0.295571   None
...            ...   ...       ...    ...
22610         None  None  0.311064   None
22611         None  None  0.444236   None
22612         None  None      None   None
22613         None  None  0.459995   None
22614         None  None  0.617612   None

[22615 rows x 9 columns]
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
        site_id                  ts      temp         rh          swp  \
0            29 2010-12-31 23:00:00      None       None         None
1            29 2011-01-01 00:00:00      None       None         None
2            29 2011-01-01 01:00:00      None       None         None
3            29 2011-01-01 02:00:00      None       None         None
4            29 2011-01-01 03:00:00      None       None         None
...         ...                 ...       ...        ...          ...
102943       29 2022-09-29 06:00:00  8.166667  98.166667  -118.736768
102944       29 2022-09-29 07:00:00  8.333333  98.166667   -97.424444
102945       29 2022-09-29 08:00:00  8.333333  98.166667   -78.993527
102946       29 2022-09-29 09:00:00  8.500000  98.500000   -74.631311
102947       29 2022-09-29 10:00:00  8.500000  98.500000   -71.351611

       total_precip         rad       vpd    vpd_bo
0          0.000000        None      None      None
1          0.000000    0.000000      None      None
2          0.000000    0.000000      None      None
3          0.000000    0.000000      None      None
4          0.000000    0.000000      None      None
...             ...         ...       ...       ...
102943     0.967000    2.000000  0.019965  0.020116
102944     0.225000   25.000000  0.020192  0.020426
102945     0.565000   81.000000  0.020192  0.020426
102946     0.000000  222.000000  0.016709  0.016712
102947     0.000000  307.000000  0.016709  0.016712

[102948 rows x 9 columns]
        site_id                  ts      temp         rh          swp  \
0            30 2010-12-31 23:00:00      None       None         None
1            30 2011-01-01 00:00:00      None       None         None
2            30 2011-01-01 01:00:00      None       None         None
3            30 2011-01-01 02:00:00      None       None         None
4            30 2011-01-01 03:00:00      None       None         None
...         ...                 ...       ...        ...          ...
102946       30 2022-09-29 09:00:00  8.500000  98.000000  -802.676831
102947       30 2022-09-29 10:00:00  9.000000  98.333333  -809.283591
102948       30 2022-09-29 11:00:00  9.500000  98.500000  -820.663680
102949       30 2022-09-29 12:00:00  9.500000  98.000000  -825.098145
102950       30 2022-09-29 13:00:00      None       None  -828.623055

       total_precip         rad       vpd    vpd_bo
0          0.000000        None      None      None
1          0.000000    0.000000      None      None
2          0.000000    0.000000      None      None
3          0.000000    0.000000      None      None
4          0.000000    0.000000      None      None
...             ...         ...       ...       ...
102946     0.000000  222.000000  0.022278  0.022283
102947     0.000000  307.000000  0.019203  0.019208
102948     0.033000  287.000000  0.017875  0.017879
102949     0.024000  376.000000  0.023834  0.023839
102950     0.052000  359.000000      None      None

[102951 rows x 9 columns]
       site_id                  ts       temp         rh   swp total_precip  \
0           31 2010-12-31 23:00:00       None       None  None     0.000000
1           31 2011-01-01 00:00:00       None       None  None     0.000000
2           31 2011-01-01 01:00:00       None       None  None     0.000000
3           31 2011-01-01 02:00:00       None       None  None     0.000000
4           31 2011-01-01 03:00:00       None       None  None     0.000000
...        ...                 ...        ...        ...   ...          ...
87668       31 2020-12-31 19:00:00  -0.500000  77.200000  None     0.485000
87669       31 2020-12-31 20:00:00  -0.500000  80.500000  None     0.113000
87670       31 2020-12-31 21:00:00  -1.000000  81.200000  None     0.306000
87671       31 2020-12-31 22:00:00  -0.500000  79.200000  None     0.105000
87672       31 2020-12-31 23:00:00  -0.500000  75.000000  None     0.090000

            rad       vpd vpd_bo
0          None      None   None
1      0.000000      None   None
2      0.000000      None   None
3      0.000000      None   None
4      0.000000      None   None
...         ...       ...    ...
87668  0.000000  0.134894   None
87669  0.000000  0.115370   None
87670  0.000000  0.107237   None
87671  0.000000  0.123061   None
87672  0.000000  0.147910   None

[87673 rows x 9 columns]
        site_id                  ts      temp         rh           swp  \
0            32 2011-01-01 00:00:00      None       None          None
1            32 2011-01-01 01:00:00      None       None          None
2            32 2011-01-01 02:00:00      None       None          None
3            32 2011-01-01 03:00:00      None       None          None
4            32 2011-01-01 04:00:00      None       None          None
...         ...                 ...       ...        ...           ...
102989       32 2022-10-01 05:00:00  8.833333  91.833333  -1145.162168
102990       32 2022-10-01 06:00:00  8.333333  92.166667  -1143.642253
102991       32 2022-10-01 07:00:00  7.833333  92.833333  -1142.095966
102992       32 2022-10-01 08:00:00  8.166667  94.000000  -1135.504163
102993       32 2022-10-01 09:00:00  9.000000  94.166667          None

       total_precip        rad       vpd    vpd_bo
0              None   0.573671      None      None
1              None   0.803139      None      None
2              None   0.688405      None      None
3              None   0.688405      None      None
4              None   0.688405      None      None
...             ...        ...       ...       ...
102989     0.000000   0.000000  0.093054  0.093543
102990     0.000000   3.000000  0.086284  0.086716
102991     0.005000  17.000000  0.076302  0.076700
102992     0.225000  34.000000  0.065346  0.065609
102993     0.330000  49.000000  0.067220  0.067227

[102994 rows x 9 columns]
        site_id                  ts       temp         rh   swp total_precip  \
0            33 2011-01-01 00:00:00       None       None  None         None
1            33 2011-01-01 01:00:00       None       None  None         None
2            33 2011-01-01 02:00:00       None       None  None         None
3            33 2011-01-01 03:00:00       None       None  None         None
4            33 2011-01-01 04:00:00       None       None  None         None
...         ...                 ...        ...        ...   ...          ...
107027       33 2023-04-11 10:00:00  10.088849  89.713308  None         None
107028       33 2023-04-11 11:00:00   9.607941  90.687892  None         None
107029       33 2023-04-11 12:00:00  12.044082  80.022442  None         None
107030       33 2023-04-11 13:00:00  13.575641  68.703246  None         None
107031       33 2023-04-11 14:00:00  14.355450  60.149718  None         None

               rad       vpd vpd_bo
0         0.575909      None   None
1         0.806273      None   None
2         0.691091      None   None
3         0.691091      None   None
4         0.691091      None   None
...            ...       ...    ...
107027  105.000000  0.127535   None
107028  160.000000  0.111790   None
107029  385.000000  0.282017   None
107030  427.000000  0.488416   None
107031  313.000000  0.654182   None

[107032 rows x 9 columns]
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []
        site_id                  ts       temp         rh         swp  \
0            36 1997-01-01 00:00:00  -8.266667  86.350000        None
1            36 1997-01-01 01:00:00  -8.383333  90.450000        None
2            36 1997-01-01 02:00:00  -8.333333  90.316667        None
3            36 1997-01-01 03:00:00  -8.200000  90.400000        None
4            36 1997-01-01 04:00:00  -7.300000  88.066667        None
...         ...                 ...        ...        ...         ...
228800       36 2023-04-07 22:00:00  -1.260583  97.458056  -32.715033

In [54]:
meta_id[972]

measure_point      pfynwald-irr_stop_dendrometer_µm_274_0_1.5_nor...
series_id                                                        972
series_start                                     2010-10-15 00:00:00
series_stop                                                      NaT
series_cutout                                                   None
                                         ...
site_growth_vpd                                                 0.74
site_n_depo                                                     None
site_ozon                                                       None
site_nfk                                                        None
site_temp_ref                                                  969.0
Name: 968, Length: 106, dtype: object

In [55]:
meta_id[972].site_id

89

In [8]:
dendro

{1:         series_id                  ts        value
 0               1 2014-05-21 12:40:00  2249.375700
 1               1 2014-05-21 12:50:00  2248.375100
 2               1 2014-05-21 13:00:00  2245.998500
 3               1 2014-05-21 13:10:00  2243.332800
 4               1 2014-05-21 13:20:00  2242.045700
 ...           ...                 ...          ...
 438930          1 2022-10-05 00:10:00  4969.418799
 438931          1 2022-10-05 00:20:00  4969.418799
 438932          1 2022-10-05 00:30:00  4969.418799
 438933          1 2022-10-05 00:40:00  4969.418799
 438934          1 2022-10-05 00:50:00  4969.418799

 [438935 rows x 3 columns],
 2:         series_id                  ts        value
 0               2 2014-05-21 13:10:00  3054.553158
 1               2 2014-05-21 13:20:00  3053.101185
 2               2 2014-05-21 13:30:00  3051.026983
 3               2 2014-05-21 13:40:00  3050.171564
 4               2 2014-05-21 13:50:00  3048.342776
 ...           ...                 ...          ...
 438929          2 2022-10-05 00:10:00  6455.667114
 438930          2 2022-10-05 00:20:00  6456.276486
 438931          2 2022-10-05 00:30:00  6456.298828
 438932          2 2022-10-05 00:40:00  6456.886800
 438933          2 2022-10-05 00:50:00  6456.909180

 [438934 rows x 3 columns],
 3:         series_id                  ts        value
 0               3 2014-05-21 12:40:00     2.516805
 1               3 2014-05-21 12:50:00    -0.532220
 2               3 2014-05-21 13:00:00    -3.092387
 3               3 2014-05-21 13:10:00    -5.176333
 4               3 2014-05-21 13:20:00    -6.878067
 ...           ...                 ...          ...
 431458          3 2022-10-05 00:10:00  7365.795627
 431459          3 2022-10-05 00:20:00  7365.795627
 431460          3 2022-10-05 00:30:00  7365.795627
 431461          3 2022-10-05 00:40:00  7365.795627
 431462          3 2022-10-05 00:50:00  7365.795627

 [431463 rows x 3 columns],
 4:         series_id                  ts         value
 0               4 2014-05-21 12:40:00   3772.214407
 1               4 2014-05-21 12:50:00   3768.554000
 2               4 2014-05-21 13:00:00   3765.468070
 3               4 2014-05-21 13:10:00   3762.413673
 4               4 2014-05-21 13:20:00   3759.363333
 ...           ...                 ...           ...
 435216          4 2022-10-05 00:10:00  11582.641602
 435217          4 2022-10-05 00:20:00  11582.641602
 435218          4 2022-10-05 00:30:00  11582.641602
 435219          4 2022-10-05 00:40:00  11582.641602
 435220          4 2022-10-05 00:50:00  11582.641602

 [435221 rows x 3 columns],
 5: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 6: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 7: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 8: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 9: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 10: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 11: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 12: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 13: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 14: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 15: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 16: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 17: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 18:         series_id                  ts         value
 0              18 2014-12-30 00:10:00     18.709339
 1              18 2014-12-30 00:20:00     18.324640
 2              18 2014-12-30 00:30:00     18.740434
 3              18 2014-12-30 00:40:00     18.149665
 4              18 2014-12-30 00:50:00     19.032270
 ...           ...                 ...           ...
 389293         18 2024-03-29 00:00:00  25225.838581
 389294         18 2024-03-29 00:10:00  25225.812196
 389295         18 2024-03-29 00:20:00  25225.771175
 389296         18 2024-03-29 00:30:00  25225.632917
 389297         18 2024-03-29 00:40:00  25225.532698

 [389298 rows x 3 columns],
 19:         series_id                  ts         value
 0              19 2012-08-29 07:50:00    895.880000
 1              19 2012-08-29 08:00:00    895.421796
 2              19 2012-08-29 08:10:00    893.850000
 3              19 2012-08-29 08:20:00    893.850000
 4              19 2012-08-29 08:30:00    893.543333
 ...           ...                 ...           ...
 542851         19 2024-03-29 00:10:00  19475.666686
 542852         19 2024-03-29 00:20:00  19475.644439
 542853         19 2024-03-29 00:30:00  19475.583169
 542854         19 2024-03-29 00:40:00  19475.598213
 542855         19 2024-03-29 00:50:00  19475.599555

 [542856 rows x 3 columns],
 20:         series_id                  ts        value
 0              20 2012-08-29 07:50:00  1040.260000
 1              20 2012-08-29 08:00:00  1040.109654
 2              20 2012-08-29 08:10:00  1040.331392
 3              20 2012-08-29 08:20:00  1039.871805
 4              20 2012-08-29 08:30:00  1039.877047
 ...           ...                 ...          ...
 465634         20 2024-03-29 00:10:00  9688.467977
 465635         20 2024-03-29 00:20:00  9688.479248
 465636         20 2024-03-29 00:30:00  9688.498634
 465637         20 2024-03-29 00:40:00  9688.457222
 465638         20 2024-03-29 00:50:00  9688.414554

 [465639 rows x 3 columns],
 21:         series_id                  ts         value
 0              21 2012-08-29 07:50:00   2100.396055
 1              21 2012-08-29 08:00:00   2099.138166
 2              21 2012-08-29 08:10:00   2098.319825
 3              21 2012-08-29 08:20:00   2097.880299
 4              21 2012-08-29 08:30:00   2097.565263
 ...           ...                 ...           ...
 454484         21 2024-03-29 00:10:00  29215.806142
 454485         21 2024-03-29 00:20:00  29215.655720
 454486         21 2024-03-29 00:30:00  29215.322341
 454487         21 2024-03-29 00:40:00  29214.798966
 454488         21 2024-03-29 00:50:00  29214.717064

 [454489 rows x 3 columns],
 22:         series_id                  ts         value
 0              22 2021-05-20 00:10:00   6191.679186
 1              22 2021-05-20 00:20:00   6188.443190
 2              22 2021-05-20 00:30:00   6185.207195
 3              22 2021-05-20 00:40:00   6181.971199
 4              22 2021-05-20 00:50:00   6178.735204
 ...           ...                 ...           ...
 149799         22 2024-03-29 00:10:00  11086.072803
 149800         22 2024-03-29 00:20:00  11086.053646
 149801         22 2024-03-29 00:30:00  11086.006311
 149802         22 2024-03-29 00:40:00  11085.864580
 149803         22 2024-03-29 00:50:00  11085.637173

 [149804 rows x 3 columns],
 23:         series_id                  ts         value
 0              23 2012-08-29 07:50:00   2841.802256
 1              23 2012-08-29 08:00:00   2841.946617
 2              23 2012-08-29 08:10:00   2841.790850
 3              23 2012-08-29 08:20:00   2841.190000
 4              23 2012-08-29 08:30:00   2839.335338
 ...           ...                 ...           ...
 507822         23 2024-03-29 00:10:00  44168.386525
 507823         23 2024-03-29 00:20:00  44168.486913
 507824         23 2024-03-29 00:30:00  44168.298610
 507825         23 2024-03-29 00:40:00  44168.323074
 507826         23 2024-03-29 00:50:00  44168.228367

 [507827 rows x 3 columns],
 24:         series_id                  ts         value
 0              24 2012-09-05 09:10:00    961.194185
 1              24 2012-09-05 09:20:00    961.715552
 2              24 2012-09-05 09:30:00    962.236920
 3              24 2012-09-05 09:40:00    962.758287
 4              24 2012-09-05 09:50:00    962.768644
 ...           ...                 ...           ...
 352054         24 2021-02-03 00:10:00  16692.591904
 352055         24 2021-02-03 00:20:00  16692.563655
 352056         24 2021-02-03 00:30:00  16692.554152
 352057         24 2021-02-03 00:40:00  16692.589938
 352058         24 2021-02-03 00:50:00  16692.596164

 [352059 rows x 3 columns],
 25: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 26: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 27:         series_id                  ts         value
 0              27 2012-06-20 15:00:00    399.900627
 1              27 2012-06-20 15:10:00    399.937864
 2              27 2012-06-20 15:20:00    399.937864
 3              27 2012-06-20 15:30:00    399.937864
 4              27 2012-06-20 15:40:00    400.476362
 ...           ...                 ...           ...
 584715         27 2024-03-29 15:30:00  12613.960923
 584716         27 2024-03-29 15:40:00  12613.025239
 584717         27 2024-03-29 15:50:00  12612.464680
 584718         27 2024-03-29 16:00:00  12611.734008
 584719         27 2024-03-29 16:10:00  12611.588328

 [584720 rows x 3 columns],
 28:         series_id                  ts        value
 0              28 2012-06-20 15:00:00   291.732155
 1              28 2012-06-20 15:10:00   301.150912
 2              28 2012-06-20 15:20:00   299.478504
 3              28 2012-06-20 15:30:00   301.820716
 4              28 2012-06-20 15:40:00   301.019417
 ...           ...                 ...          ...
 590128         28 2024-03-29 15:20:00  4473.081756
 590129         28 2024-03-29 15:30:00  4473.324953
 590130         28 2024-03-29 15:40:00  4473.380705
 590131         28 2024-03-29 15:50:00  4473.723039
 590132         28 2024-03-29 16:00:00  4473.810391

 [590133 rows x 3 columns],
 29:         series_id                  ts        value
 0              29 2012-06-20 14:50:00   150.916062
 1              29 2012-06-20 15:00:00   151.727321
 2              29 2012-06-20 15:10:00   138.382493
 3              29 2012-06-20 15:20:00   133.131830
 4              29 2012-06-20 15:30:00   132.092857
 ...           ...                 ...          ...
 590232         29 2024-03-29 15:20:00  7984.017196
 590233         29 2024-03-29 15:30:00  7983.904596
 590234         29 2024-03-29 15:40:00  7985.952992
 590235         29 2024-03-29 15:50:00  7981.997677
 590236         29 2024-03-29 16:00:00  7980.401306

 [590237 rows x 3 columns],
 30:         series_id                  ts         value
 0              30 2012-06-20 15:10:00    800.000000
 1              30 2012-06-20 15:20:00    799.656080
 2              30 2012-06-20 15:30:00    799.063530
 3              30 2012-06-20 15:40:00    796.820450
 4              30 2012-06-20 15:50:00    795.756610
 ...           ...                 ...           ...
 590048         30 2024-03-29 15:30:00  33644.230932
 590049         30 2024-03-29 15:40:00  33645.896851
 590050         30 2024-03-29 15:50:00  33646.624490
 590051         30 2024-03-29 16:00:00  33646.692871
 590052         30 2024-03-29 16:10:00  33646.790879

 [590053 rows x 3 columns],
 31:         series_id                  ts         value
 0              31 2012-06-20 14:50:00    478.930829
 1              31 2012-06-20 15:00:00    478.930829
 2              31 2012-06-20 15:10:00    478.930829
 3              31 2012-06-20 15:20:00    478.930829
 4              31 2012-06-20 15:30:00    478.930829
 ...           ...                 ...           ...
 589949         31 2024-03-29 15:30:00  14331.129387
 589950         31 2024-03-29 15:40:00  14330.411280
 589951         31 2024-03-29 15:50:00  14329.492570
 589952         31 2024-03-29 16:00:00  14328.778173
 589953         31 2024-03-29 16:10:00  14328.523388

 [589954 rows x 3 columns],
 32:         series_id                  ts         value
 0              32 2012-06-20 15:10:00    127.133860
 1              32 2012-06-20 15:20:00    126.572507
 2              32 2012-06-20 15:30:00    128.415928
 3              32 2012-06-20 15:40:00    128.704446
 4              32 2012-06-20 15:50:00    128.935399
 ...           ...                 ...           ...
 585170         32 2024-03-29 15:30:00  39164.572514
 585171         32 2024-03-29 15:40:00  39163.641510
 585172         32 2024-03-29 15:50:00  39163.349696
 585173         32 2024-03-29 16:00:00  39161.993046
 585174         32 2024-03-29 16:10:00  39161.603374

 [585175 rows x 3 columns],
 33: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 34: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 35: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 36: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 37: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 38: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 39: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 40: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 41: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 42: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 43: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 44: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 45: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 46: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 47: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 48: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 49: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 50: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 51: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 52: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 53:        series_id                  ts        value
 0             53 2023-03-22 01:10:00  3869.780489
 1             53 2023-03-22 01:20:00  3869.788647
 2             53 2023-03-22 01:30:00  3869.779395
 3             53 2023-03-22 01:40:00  3869.782293
 4             53 2023-03-22 01:50:00  3869.778339
 ...          ...                 ...          ...
 54091         53 2024-04-01 00:10:00  9197.253489
 54092         53 2024-04-01 00:20:00  9197.239148
 54093         53 2024-04-01 00:30:00  9197.223880
 54094         53 2024-04-01 00:40:00  9197.208179
 54095         53 2024-04-01 00:50:00  9197.191131

 [54096 rows x 3 columns],
 54:        series_id                  ts         value
 0             54 2023-03-22 01:10:00   8190.418129
 1             54 2023-03-22 01:20:00   8190.427122
 2             54 2023-03-22 01:30:00   8190.451810
 3             54 2023-03-22 01:40:00   8190.470471
 4             54 2023-03-22 01:50:00   8190.458352
 ...          ...                 ...           ...
 54090         54 2024-04-01 00:10:00  10268.937907
 54091         54 2024-04-01 00:20:00  10268.973255
 54092         54 2024-04-01 00:30:00  10269.002192
 54093         54 2024-04-01 00:40:00  10269.013251
 54094         54 2024-04-01 00:50:00  10269.031102

 [54095 rows x 3 columns],
 55: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 56: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 57: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 58: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 59: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 60: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 61: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 62: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 63: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 64: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 65: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 66: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 67: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 68: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 69: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 70: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 71: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 72:         series_id                  ts         value
 0              72 2018-06-04 11:10:00   9931.431492
 1              72 2018-06-04 11:20:00   9923.953345
 2              72 2018-06-04 11:30:00   9920.954609
 3              72 2018-06-04 11:40:00   9920.015717
 4              72 2018-06-04 11:50:00   9919.525814
 ...           ...                 ...           ...
 240579         72 2024-04-01 00:10:00  27163.829132
 240580         72 2024-04-01 00:20:00  27163.840345
 240581         72 2024-04-01 00:30:00  27163.849338
 240582         72 2024-04-01 00:40:00  27163.882760
 240583         72 2024-04-01 00:50:00  27163.929485

 [240584 rows x 3 columns],
 73:         series_id                  ts        value
 0              73 2014-09-08 15:10:00   -81.610000
 1              73 2014-09-08 15:20:00   -82.527798
 2              73 2014-09-08 15:30:00   -83.870917
 3              73 2014-09-08 15:40:00   -85.214037
 4              73 2014-09-08 15:50:00   -84.685417
 ...           ...                 ...          ...
 312186         73 2021-01-11 12:50:00  9037.449707
 312187         73 2021-01-11 13:00:00  9037.449707
 312188         73 2021-01-11 13:10:00  9037.449707
 312189         73 2021-01-11 13:20:00  9037.449707
 312190         73 2021-01-11 13:30:00  9037.449707

 [312191 rows x 3 columns],
 74:         series_id                  ts         value
 0              74 2018-06-04 11:00:00   5322.581460
 1              74 2018-06-04 11:10:00   5318.118310
 2              74 2018-06-04 11:20:00   5314.345765
 3              74 2018-06-04 11:30:00   5310.618663
 4              74 2018-06-04 11:40:00   5305.125622
 ...           ...                 ...           ...
 230931         74 2024-04-01 00:10:00  37456.644807
 230932         74 2024-04-01 00:20:00  37456.663859
 230933         74 2024-04-01 00:30:00  37456.929064
 230934         74 2024-04-01 00:40:00  37457.088066
 230935         74 2024-04-01 00:50:00  37457.112232

 [230936 rows x 3 columns],
 75:         series_id                  ts         value
 0              75 2014-09-10 01:10:00    125.915383
 1              75 2014-09-10 01:20:00    128.355383
 2              75 2014-09-10 01:30:00    130.376517
 3              75 2014-09-10 01:40:00    132.213383
 4              75 2014-09-10 01:50:00    134.465383
 ...           ...                 ...           ...
 355181         75 2022-06-09 03:20:00  18088.455620
 355182         75 2022-06-09 03:30:00  18088.687132
 355183         75 2022-06-09 03:40:00  18088.687132
 355184         75 2022-06-09 03:50:00  18088.687132
 355185         75 2022-06-09 04:00:00  18088.687132

 [355186 rows x 3 columns],
 76: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 77: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 78: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 79: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 80: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 81: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 82: Empty DataFrame
 Columns: [series_id, ts, value]
 Index: [],
 83:        series_id                  ts         value
 0             83 2023-03-22 01:10:00  10297.067397
 1             83 2023-03-22 01:20:00  10297.006307
 2             83 2023-03-22 01:30:00  10297.011544
 3             83 2023-03-22 01:40:00  10297.040780
 4             83 2023-03-22 01:50:00  10297.067460
 ...          ...                 ...           ...
 54088         83 2024-04-01 00:10:00  11491.289139
 54089         83 2024-04-01 00:20:00  11491.290025
 54090         83 2024-04-01 00:30:00  11491.291523
 54091         83 2024-04-01 00:40:00  11491.306680
 54092         83 2024-04-01 00:50:00  11491.345443

 [54093 rows x 3 columns],
 84:        series_id                  ts         value
 0             84 2023-03-22 01:10:00   6772.980504
 1             84 2023-03-22 01:20:00   6772.830025

In [68]:
i=192
a = pd.merge(dendro[i], clima[meta_id[i].site_id], on = "ts", how = "outer")
a

,series_id,ts,value,site_id,temp,rh,swp,total_precip,rad,vpd,vpd_bo
0,192,2018-11-30 19:20:00,1064.025829,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,192,2018-11-30 19:30:00,1063.951920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,192,2018-11-30 19:40:00,1063.878010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,192,2018-11-30 19:50:00,1063.804100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,192,2018-11-30 20:00:00,1063.768337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
273280,192,2024-04-01 00:10:00,14036.880882,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273281,192,2024-04-01 00:20:00,14036.894599,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273282,192,2024-04-01 00:30:00,14036.875857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273283,192,2024-04-01 00:40:00,14036.877328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
273284,192,2024-04-01 00:50:00,14036.910164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
meta_id[i].site_id

34

In [81]:
clima[34]

Empty DataFrame
Columns: [site_id, ts, temp, rh, swp, total_precip, rad, vpd, vpd_bo]
Index: []

In [48]:
b = a [a.value.first_valid_index():a.value.last_valid_index()]
b

,series_id,ts,value,site_id,temp,rh,swp,total_precip,rad,vpd,vpd_bo
0,972,2010-10-15 20:40:00,5048.830000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,972,2010-10-15 20:50:00,5048.830000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,972,2010-10-15 21:00:00,5048.830000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,972,2010-10-15 21:10:00,5048.830000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,972,2010-10-15 21:20:00,5048.830000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
680897,972,2024-04-18 00:00:00,10497.323420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
680898,972,2024-04-18 00:10:00,10497.933960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
680899,972,2024-04-18 00:20:00,10499.041748,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
680900,972,2024-04-18 00:30:00,10499.765845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
680901,972,2024-04-18 00:40:00,10500.375554,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
c = b[["series_id", "site_id", "ts", "value", "temp", "rh", "swp", "total_precip", "rad", "vpd"]].rename(columns={"value": "stem_radius"})
c

,series_id,site_id,ts,stem_radius,temp,rh,swp,total_precip,rad,vpd
0,972,NaN,2010-10-15 20:40:00,5048.830000,NaN,NaN,NaN,NaN,NaN,NaN
1,972,NaN,2010-10-15 20:50:00,5048.830000,NaN,NaN,NaN,NaN,NaN,NaN
2,972,NaN,2010-10-15 21:00:00,5048.830000,NaN,NaN,NaN,NaN,NaN,NaN
3,972,NaN,2010-10-15 21:10:00,5048.830000,NaN,NaN,NaN,NaN,NaN,NaN
4,972,NaN,2010-10-15 21:20:00,5048.830000,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
680897,972,NaN,2024-04-18 00:00:00,10497.323420,NaN,NaN,NaN,NaN,NaN,NaN
680898,972,NaN,2024-04-18 00:10:00,10497.933960,NaN,NaN,NaN,NaN,NaN,NaN
680899,972,NaN,2024-04-18 00:20:00,10499.041748,NaN,NaN,NaN,NaN,NaN,NaN
680900,972,NaN,2024-04-18 00:30:00,10499.765845,NaN,NaN,NaN,NaN,NaN,NaN
680901,972,NaN,2024-04-18 00:40:00,10500.375554,NaN,NaN,NaN,NaN,NaN,NaN

In [1]:
c['site_id'] = c['site_id'].ffill().bfill().astype(int)
c['series_id'] = c['series_id'].ffill().bfill().astype(int)
c

NameError: name 'c' is not defined

In [25]:
start = c.ts.iloc[0]
end = c.ts.iloc[-1]
complete_times = {'ts': pd.date_range(start=start, end=end, freq='10Min')}

In [26]:
d = pd.merge(c, pd.DataFrame(complete_times), on = "ts", how = "outer")
d

,series_id,site_id,ts,stem_radius,temp,rh,swp,total_precip,rad,vpd
0,1593.0,NaN,2024-02-14 01:10:00,4835.514915,NaN,NaN,NaN,NaN,NaN,NaN
1,1593.0,NaN,2024-02-14 01:20:00,4835.542270,NaN,NaN,NaN,NaN,NaN,NaN
2,1593.0,NaN,2024-02-14 01:30:00,4835.572211,NaN,NaN,NaN,NaN,NaN,NaN
3,1593.0,NaN,2024-02-14 01:40:00,4835.597173,NaN,NaN,NaN,NaN,NaN,NaN
4,1593.0,NaN,2024-02-14 01:50:00,4835.587907,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
6094,1593.0,NaN,2024-03-27 08:50:00,2007.491677,NaN,NaN,NaN,NaN,NaN,NaN
6095,1593.0,NaN,2024-03-27 09:00:00,2005.376232,NaN,NaN,NaN,NaN,NaN,NaN
6096,1593.0,NaN,2024-03-27 09:10:00,2003.249014,NaN,NaN,NaN,NaN,NaN,NaN
6097,1593.0,NaN,2024-03-27 09:20:00,2000.491373,NaN,NaN,NaN,NaN,NaN,NaN
6098,1593.0,NaN,2024-03-27 09:30:00,1997.684521,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df = {} # Initialize dictionary
    
for key, value in dendro.items():
    if len(value) > 0:
        a = pd.merge(value, clima[meta_id[key].site_id], on = "ts", how = "outer")
        b = a [a.value.first_valid_index():a.value.last_valid_index()]
        c = b[["series_id", "site_id", "ts", "value", "temp", "rh", "swp", "total_precip", "rad", "vpd"]].rename(columns={"value": "stem_radius"})
        start = c.ts.iloc[0]
        end = c.ts.iloc[-1]
        complete_times = {'ts': pd.date_range(start=start, end=end, freq='10Min')} 

        d = pd.merge(c, pd.DataFrame(complete_times), on = "ts", how = "outer")
        df[key] = d

In [20]:
clima[meta_id[3].site_id]

,site_id,ts,temp,rh,swp,total_precip,rad,vpd,vpd_bo
0,2,2011-10-13 09:00:00,None,None,None,0.000000,None,None,None
1,2,2011-10-13 10:00:00,None,None,None,0.000000,412.166667,None,None
2,2,2011-10-13 11:00:00,None,None,None,0.000000,352.833333,None,None
3,2,2011-10-13 12:00:00,None,None,None,0.000000,452.333333,None,None
4,2,2011-10-13 13:00:00,None,None,None,0.000000,587.166667,None,None
...,...,...,...,...,...,...,...,...,...
96235,2,2022-10-05 04:00:00,8.333333,45.333333,-11.326052,0.000000,0.000000,0.601975,0.602865
96236,2,2022-10-05 05:00:00,8.166667,43.500000,-11.328660,0.000000,0.000000,0.615162,0.615852
96237,2,2022-10-05 06:00:00,8.500000,41.833333,-11.329960,0.000000,7.000000,0.647797,0.648058
96238,2,2022-10-05 07:00:00,8.666667,39.500000,-11.331269,0.000000,24.000000,0.681431,0.681974
96239,2,2022-10-05 08:00:00,9.166667,42.500000,-11.333870,0.000000,245.000000,0.669885,0.670494

In [21]:
df[3]

,series_id,site_id,ts,stem_radius,temp,rh,swp,total_precip,rad,vpd
0,3.0,NaN,2014-05-21 12:40:00,2.516805,NaN,NaN,NaN,NaN,NaN,NaN
1,3.0,NaN,2014-05-21 12:50:00,-0.532220,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,2.0,2014-05-21 13:00:00,-3.092387,21.000000,35.000000,-10.659580,0.000000,621.104034,1.621833
3,3.0,NaN,2014-05-21 13:10:00,-5.176333,NaN,NaN,NaN,NaN,NaN,NaN
4,3.0,NaN,2014-05-21 13:20:00,-6.878067,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
440420,3.0,2.0,2022-10-05 00:00:00,7365.795627,8.666667,49.500000,-11.316924,0.000000,0.000000,0.568798
440421,3.0,NaN,2022-10-05 00:10:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN
440422,3.0,NaN,2022-10-05 00:20:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN
440423,3.0,NaN,2022-10-05 00:30:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN
440424,3.0,NaN,2022-10-05 00:40:00,7365.795627,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
combined_data = dpl.load_dataframe("/storage/lukovic/Data/FORWARDS/treenet/server_data/combined_dendro_climate_dictionary.pkl")

In [3]:
a = combined_data[2]

In [9]:
a.tail()

,series_id,site_id,ts,stem_radius,temp,rh,swp,total_precip,rad,vpd
440417,2.0,2.0,2022-10-05 00:00:00,6455.056763,8.500000,51.833333,-11.325561,0.000000,0.000000,0.536419
440418,2.0,2.0,2022-10-05 00:10:00,6455.667114,NaN,NaN,NaN,NaN,NaN,NaN
440419,2.0,2.0,2022-10-05 00:20:00,6456.276486,NaN,NaN,NaN,NaN,NaN,NaN
440420,2.0,2.0,2022-10-05 00:30:00,6456.298828,NaN,NaN,NaN,NaN,NaN,NaN
440421,2.0,2.0,2022-10-05 00:40:00,6456.886800,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
for key, value in combined_data.items():
    print(key, value)

1         series_id  site_id                  ts  stem_radius       temp  \
0             1.0      1.0 2014-05-21 12:40:00  2249.375700        NaN
1             1.0      1.0 2014-05-21 12:50:00  2248.375100        NaN
2             1.0      1.0 2014-05-21 13:00:00  2245.998500  21.500000
3             1.0      1.0 2014-05-21 13:10:00  2243.332800        NaN
4             1.0      1.0 2014-05-21 13:20:00  2242.045700        NaN
...           ...      ...                 ...          ...        ...
440420        1.0      1.0 2022-10-05 00:00:00  4969.418799   8.500000
440421        1.0      1.0 2022-10-05 00:10:00  4969.418799        NaN
440422        1.0      1.0 2022-10-05 00:20:00  4969.418799        NaN
440423        1.0      1.0 2022-10-05 00:30:00  4969.418799        NaN
440424        1.0      1.0 2022-10-05 00:40:00  4969.418799        NaN

               rh         swp total_precip         rad       vpd
0             NaN         NaN          NaN         NaN       NaN
1             NaN         NaN          NaN         NaN       NaN
2       34.833330  -10.292638     0.000000  622.552230  1.676604
3             NaN         NaN          NaN         NaN       NaN
4             NaN         NaN          NaN         NaN       NaN
...           ...         ...          ...         ...       ...
440420  51.833333  -11.325561     0.000000    0.000000  0.536419
440421        NaN         NaN          NaN         NaN       NaN
440422        NaN         NaN          NaN         NaN       NaN
440423        NaN         NaN          NaN         NaN       NaN
440424        NaN         NaN          NaN         NaN       NaN

[440425 rows x 10 columns]
2         series_id  site_id                  ts  stem_radius      temp  \
0             2.0      1.0 2014-05-21 13:10:00  3054.553158       NaN
1             2.0      1.0 2014-05-21 13:20:00  3053.101185       NaN
2             2.0      1.0 2014-05-21 13:30:00  3051.026983       NaN
3             2.0      1.0 2014-05-21 13:40:00  3050.171564       NaN
4             2.0      1.0 2014-05-21 13:50:00  3048.342776       NaN
...           ...      ...                 ...          ...       ...
440417        2.0      1.0 2022-10-05 00:00:00  6455.056763  8.500000
440418        2.0      1.0 2022-10-05 00:10:00  6455.667114       NaN
440419        2.0      1.0 2022-10-05 00:20:00  6456.276486       NaN
440420        2.0      1.0 2022-10-05 00:30:00  6456.298828       NaN
440421        2.0      1.0 2022-10-05 00:40:00  6456.886800       NaN

               rh         swp total_precip       rad       vpd
0             NaN         NaN          NaN       NaN       NaN
1             NaN         NaN          NaN       NaN       NaN
2             NaN         NaN          NaN       NaN       NaN
3             NaN         NaN          NaN       NaN       NaN
4             NaN         NaN          NaN       NaN       NaN
...           ...         ...          ...       ...       ...
440417  51.833333  -11.325561     0.000000  0.000000  0.536419
440418        NaN         NaN          NaN       NaN       NaN
440419        NaN         NaN          NaN       NaN       NaN
440420        NaN         NaN          NaN       NaN       NaN
440421        NaN         NaN          NaN       NaN       NaN

[440422 rows x 10 columns]
3         series_id  site_id                  ts  stem_radius       temp  \
0             3.0      2.0 2014-05-21 12:40:00     2.516805        NaN
1             3.0      2.0 2014-05-21 12:50:00    -0.532220        NaN
2             3.0      2.0 2014-05-21 13:00:00    -3.092387  21.000000
3             3.0      2.0 2014-05-21 13:10:00    -5.176333        NaN
4             3.0      2.0 2014-05-21 13:20:00    -6.878067        NaN
...           ...      ...                 ...          ...        ...
440420        3.0      2.0 2022-10-05 00:00:00  7365.795627   8.666667
440421        3.0      2.0 2022-10-05 00:10:00  7365.795627        NaN
440422        3.0      2.0 2022-10-05 00:20:00  7365.795627        NaN
440423        3.0      2.0 2022-10-05 00:30:00  7365.795627        NaN
440424        3.0      2.0 2022-10-05 00:40:00  7365.795627        NaN

               rh         swp total_precip         rad       vpd
0             NaN         NaN          NaN         NaN       NaN
1             NaN         NaN          NaN         NaN       NaN
2       35.000000  -10.659580     0.000000  621.104034  1.621833
3             NaN         NaN          NaN         NaN       NaN
4             NaN         NaN          NaN         NaN       NaN
...           ...         ...          ...         ...       ...
440420  49.500000  -11.316924     0.000000    0.000000  0.568798
440421        NaN         NaN          NaN         NaN       NaN
440422        NaN         NaN          NaN         NaN       NaN
440423        NaN         NaN          NaN         NaN       NaN
440424        NaN         NaN          NaN         NaN       NaN

[440425 rows x 10 columns]
4         series_id  site_id                  ts   stem_radius       temp  \
0             4.0      2.0 2014-05-21 12:40:00   3772.214407        NaN
1             4.0      2.0 2014-05-21 12:50:00   3768.554000        NaN
2             4.0      2.0 2014-05-21 13:00:00   3765.468070  21.000000
3             4.0      2.0 2014-05-21 13:10:00   3762.413673        NaN
4             4.0      2.0 2014-05-21 13:20:00   3759.363333        NaN
...           ...      ...                 ...           ...        ...
440420        4.0      2.0 2022-10-05 00:00:00  11582.641602   8.666667
440421        4.0      2.0 2022-10-05 00:10:00  11582.641602        NaN
440422        4.0      2.0 2022-10-05 00:20:00  11582.641602        NaN
440423        4.0      2.0 2022-10-05 00:30:00  11582.641602        NaN
440424        4.0      2.0 2022-10-05 00:40:00  11582.641602        NaN

               rh         swp total_precip         rad       vpd
0             NaN         NaN          NaN         NaN       NaN
1             NaN         NaN          NaN         NaN       NaN
2       35.000000  -10.659580     0.000000  621.104034  1.621833
3             NaN         NaN          NaN         NaN       NaN
4             NaN         NaN          NaN         NaN       NaN
...           ...         ...          ...         ...       ...
440420  49.500000  -11.316924     0.000000    0.000000  0.568798
440421        NaN         NaN          NaN         NaN       NaN
440422        NaN         NaN          NaN         NaN       NaN
440423        NaN         NaN          NaN         NaN       NaN
440424        NaN         NaN          NaN         NaN       NaN

[440425 rows x 10 columns]
18         series_id  site_id                  ts   stem_radius temp   rh  swp  \
0            18.0      3.0 2014-12-30 00:10:00     18.709339  NaN  NaN  NaN
1            18.0      3.0 2014-12-30 00:20:00     18.324640  NaN  NaN  NaN
2            18.0      3.0 2014-12-30 00:30:00     18.740434  NaN  NaN  NaN
3            18.0      3.0 2014-12-30 00:40:00     18.149665  NaN  NaN  NaN
4            18.0      3.0 2014-12-30 00:50:00     19.032270  NaN  NaN  NaN
...           ...      ...                 ...           ...  ...  ...  ...
486286       18.0      3.0 2024-03-28 23:50:00  25225.897834  NaN  NaN  NaN
486287       18.0      3.0 2024-03-29 00:00:00  25225.838581  NaN  NaN  NaN
486288       18.0      3.0 2024-03-29 00:10:00  25225.812196  NaN  NaN  NaN
486289       18.0      3.0 2024-03-29 00:20:00  25225.771175  NaN  NaN  NaN
486290       18.0      3.0 2024-03-29 00:30:00  25225.632917  NaN  NaN  NaN

       total_precip  rad  vpd
0               NaN  NaN  NaN
1               NaN  NaN  NaN
2               NaN  NaN  NaN
3               NaN  NaN  NaN
4               NaN  NaN  NaN
...             ...  ...  ...
486286          NaN  NaN  NaN
486287          NaN  NaN  NaN
486288          NaN  NaN  NaN
486289          NaN  NaN  NaN
486290          NaN  NaN  NaN

[486291 rows x 10 columns]
19         series_id  site_id                  ts   stem_radius       temp  \
0            19.0      3.0 2012-08-29 07:50:00    895.880000        NaN
1            19.0      3.0 2012-08-29 08:00:00    895.421796  18.956629
2            19.0      3.0 2012-08-29 08:10:00    893.850000        NaN
3            19.0      3.0 2012-08-29 08:20:00    893.850000        NaN
4            19.0      3.0 2012-08-29 08:30:00    893.543333        NaN
...           ...      ...                 ...           ...        ...
609073       19.0      3.0 2024-03-29 00:00:00  19475.639085        NaN
609074       19.0      3.0 2024-03-29 00:10:00  19475.666686        NaN
609075       19.0      3.0 2024-03-29 00:20:00  19475.644439        NaN
609076       19.0      3.0 2024-03-29 00:30:00  19475.583169        NaN
609077       19.0      3.0 2024-03-29 00:40:00  19475.598213        NaN

               rh   swp total_precip         rad       vpd
0             NaN   NaN          NaN         NaN       NaN
1       61.848548  None     0.000000  216.385746  0.838872
2             NaN   NaN          NaN         NaN       NaN
3             NaN   NaN          NaN         NaN       NaN
4             NaN   NaN          NaN         NaN       NaN
...           ...   ...          ...         ...       ...
609073        NaN   NaN          NaN         NaN       NaN
609074        NaN   NaN          NaN         NaN       NaN
609075        NaN   NaN          NaN         NaN       NaN
609076        NaN   NaN          NaN         NaN       NaN
609077        NaN   NaN          NaN         NaN       NaN

[609078 rows x 10 columns]
20         series_id  site_id                  ts  stem_radius       temp  \
0            20.0      3.0 2012-08-29 07:50:00  1040.260000        NaN
1            20.0      3.0 2012-08-29 08:00:00  1040.109654  18.956629
2            20.0      3.0 2012-08-29 08:10:00  1040.331392        NaN
3            20.0      3.0 2012-08-29 08:20:00  1039.871805        NaN
4            20.0      3.0 2012-08-29 08:30:00  1039.877047        NaN
...           ...      ...                 ...          ...        ...
609073       20.0      3.0 2024-03-29 00:00:00  9688.471268        NaN
609074       20.0      3.0 2024-03-29 00:10:00  9688.467977        NaN
609075       20.0      3.0 2024-03-29 00:20:00  9688.479248        NaN
609076       20.0      3.0 2024-03-29 00:30:00  9688.498634        NaN
609077       20.0      3.0 2024-03-29 00:40:00  9688.457222        NaN

               rh   swp total_precip         rad       vpd
0             NaN   NaN          NaN         NaN       NaN
1       61.848548  None     0.000000  216.385746  0.838872
2             NaN   NaN          NaN         NaN       NaN
3             NaN   NaN          NaN         NaN       NaN
4             NaN   NaN          NaN         NaN       NaN
...           ...   ...          ...         ...       ...
609073        NaN   NaN          NaN         NaN       NaN
609074        NaN   NaN          NaN         NaN       NaN
609075        NaN   NaN          NaN         NaN       NaN
609076        NaN   NaN          NaN         NaN       NaN
609077        NaN   NaN          NaN         NaN       NaN

[609078 rows x 10 columns]
21         series_id  site_id                  ts   stem_radius       temp  \
0            21.0      3.0 2012-08-29 07:50:00   2100.396055        NaN
1            21.0      3.0 2012-08-29 08:00:00   2099.138166  18.956629
2            21.0      3.0 2012-08-29 08:10:00   2098.319825        NaN
3            21.0      3.0 2012-08-29 08:20:00   2097.880299        NaN
4            21.0      3.0 2012-08-29 08:30:00   2097.565263        NaN
...           ...      ...                 ...           ...        ...
609073       21.0      3.0 2024-03-29 00:00:00  29216.217539        NaN
609074       21.0      3.0 2024-03-29 00:10:00  29215.806142        NaN
609075       21.0      3.0 2024-03-29 00:20:00  29215.655720        NaN
609076       21.0      3.0 2024-03-29 00:30:00  29215.322341        NaN
609077       21.0      3.0 2024-03-29 00:40:00  29214.798966        NaN

               rh   swp total_precip         rad       vpd
0             NaN   NaN          NaN         NaN       NaN
1       61.848548  None     0.000000  216.385746  0.838872
2             NaN   NaN          NaN         NaN       NaN
3             NaN   NaN          NaN         NaN       NaN
4             NaN   NaN          NaN         NaN       NaN
...           ...   ...          ...         ...       ...
609073        NaN   NaN          NaN         NaN       NaN
609074        NaN   NaN          NaN         NaN       NaN
609075        NaN   NaN          NaN         NaN       NaN
609076        NaN   NaN          NaN         NaN       NaN
609077        NaN   NaN          NaN         NaN       NaN

[609078 rows x 10 columns]
22         series_id  site_id                  ts   stem_radius temp   rh  swp  \
0            22.0      3.0 2021-05-20 00:10:00   6191.679186  NaN  NaN  NaN
1            22.0      3.0 2021-05-20 00:20:00   6188.443190  NaN  NaN  NaN
2            22.0      3.0 2021-05-20 00:30:00   6185.207195  NaN  NaN  NaN
3            22.0      3.0 2021-05-20 00:40:00   6181.971199  NaN  NaN  NaN
4            22.0      3.0 2021-05-20 00:50:00   6178.735204  NaN  NaN  NaN
...           ...      ...                 ...           ...  ...  ...  ...
150335       22.0      3.0 2024-03-29 00:00:00  11086.115581  NaN  NaN  NaN
150336       22.0      3.0 2024-03-29 00:10:00  11086.072803  NaN  NaN  NaN
150337       22.0      3.0 2024-03-29 00:20:00  11086.053646  NaN  NaN  NaN
150338       22.0      3.0 2024-03-29 00:30:00  11086.006311  NaN  NaN  NaN
150339       22.0      3.0 2024-03-29 00:40:00  11085.864580  NaN  NaN  NaN

       total_precip  rad  vpd
0               NaN  NaN  NaN
1               NaN  NaN  NaN
2               NaN  NaN  NaN
3               NaN  NaN  NaN
4               NaN  NaN  NaN
...             ...  ...  ...
150335          NaN  NaN  NaN
150336          NaN  NaN  NaN
150337          NaN  NaN  NaN
150338          NaN  NaN  NaN
150339          NaN  NaN  NaN

[150340 rows x 10 columns]
23         series_id  site_id                  ts   stem_radius       temp  \
0            23.0      3.0 2012-08-29 07:50:00   2841.802256        NaN
1            23.0      3.0 2012-08-29 08:00:00   2841.946617  18.956629
2            23.0      3.0 2012-08-29 08:10:00   2841.790850        NaN
3            23.0      3.0 2012-08-29 08:20:00   2841.190000        NaN
4            23.0      3.0 2012-08-29 08:30:00   2839.335338        NaN
...           ...      ...                 ...           ...        ...
609073       23.0      3.0 2024-03-29 00:00:00  44168.309133        NaN
609074       23.0      3.0 2024-03-29 00:10:00  44168.386525        NaN
609075       23.0      3.0 2024-03-29 00:20:00  44168.486913        NaN
609076       23.0      3.0 2024-03-29 00:30:00  44168.298610        NaN
609077       23.0      3.0 2024-03-29 00:40:00  44168.323074        NaN

               rh   swp total_precip         rad       vpd
0             NaN   NaN          NaN         NaN       NaN
1       61.848548  None     0.000000  216.385746  0.838872
2             NaN   NaN          NaN         NaN       NaN
3             NaN   NaN          NaN         NaN       NaN
4             NaN   NaN          NaN         NaN       NaN
...           ...   ...          ...         ...       ...
609073        NaN   NaN          NaN         NaN       NaN
609074        NaN   NaN          NaN         NaN       NaN
609075        NaN   NaN          NaN         NaN       NaN
609076        NaN   NaN          NaN         NaN       NaN
609077        NaN   NaN          NaN         NaN       NaN

[609078 rows x 10 columns]
24         series_id  site_id                  ts   stem_radius      temp  \
0            24.0      3.0 2012-09-05 09:10:00    961.194185       NaN
1            24.0      3.0 2012-09-05 09:20:00    961.715552       NaN
2            24.0      3.0 2012-09-05 09:30:00    962.236920       NaN
3            24.0      3.0 2012-09-05 09:40:00    962.758287       NaN
4            24.0      3.0 2012-09-05 09:50:00    962.768644       NaN
...           ...      ...                 ...           ...       ...
442457       24.0      3.0 2021-02-03 00:00:00  16692.598082  5.011768
442458       24.0      3.0 2021-02-03 00:10:00  16692.591904       NaN
442459       24.0      3.0 2021-02-03 00:20:00  16692.563655       NaN
442460       24.0      3.0 2021-02-03 00:30:00  16692.554152       NaN
442461       24.0      3.0 2021-02-03 00:40:00  16692.589938       NaN

               rh        swp total_precip       rad       vpd
0             NaN        NaN          NaN       NaN       NaN
1             NaN        NaN          NaN       NaN       NaN
2             NaN        NaN          NaN       NaN       NaN
3             NaN        NaN          NaN       NaN       NaN
4             NaN        NaN          NaN       NaN       NaN
...           ...        ...          ...       ...       ...
442457  91.962803  -9.500000     0.179000  0.000000  0.070438
442458        NaN        NaN          NaN       NaN       NaN
442459        NaN        NaN          NaN       NaN       NaN
442460        NaN        NaN          NaN       NaN       NaN
442461        NaN        NaN          NaN       NaN       NaN

[442462 rows x 10 columns]
27         series_id  site_id                  ts   stem_radius       temp  \
0            27.0      4.0 2012-06-20 15:00:00    399.900627  14.266667
1            27.0      4.0 2012-06-20 15:10:00    399.937864        NaN
2            27.0      4.0 2012-06-20 15:20:00    399.937864        NaN
3            27.0      4.0 2012-06-20 15:30:00    399.937864        NaN
4            27.0      4.0 2012-06-20 15:40:00    400.476362        NaN
...           ...      ...                 ...           ...        ...
619202       27.0      4.0 2024-03-29 15:20:00  12614.711415        NaN
619203       27.0      4.0 2024-03-29 15:30:00  12613.960923        NaN
619204       27.0      4.0 2024-03-29 15:40:00  12613.025239        NaN
619205       27.0      4.0 2024-03-29 15:50:00  12612.464680        NaN
619206       27.0      4.0 2024-03-29 16:00:00  12611.734008        NaN

               rh   swp total_precip         rad       vpd
0       75.700000  None     0.000000  251.000000  0.396490
1             NaN   NaN          NaN         NaN       NaN
2             NaN   NaN          NaN         NaN       NaN
3             NaN   NaN          NaN         NaN       NaN
4             NaN   NaN          NaN         NaN       NaN
...           ...   ...          ...         ...       ...
619202        NaN   NaN          NaN         NaN       NaN
619203        NaN   NaN          NaN         NaN       NaN
619204        NaN   NaN          NaN         NaN       NaN
619205        NaN   NaN          NaN         NaN       NaN
619206        NaN   NaN          NaN         NaN       NaN

[619207 rows x 10 columns]
28         series_id  site_id                  ts  stem_radius       temp  \
0            28.0      4.0 2012-06-20 15:00:00   291.732155  14.266667
1            28.0      4.0 2012-06-20 15:10:00   301.150912        NaN
2            28.0      4.0 2012-06-20 15:20:00   299.478504        NaN
3            28.0      4.0 2012-06-20 15:30:00   301.820716        NaN
4            28.0      4.0 2012-06-20 15:40:00   301.019417        NaN
...           ...      ...                 ...          ...        ...
619201       28.0      4.0 2024-03-29 15:10:00  4473.007071        NaN
619202       28.0      4.0 2024-03-29 15:20:00  4473.081756        NaN
619203       28.0      4.0 2024-03-29 15:30:00  4473.324953        NaN
619204       28.0      4.0 2024-03-29 15:40:00  4473.380705        NaN
619205       28.0      4.0 2024-03-29 15:50:00  4473.723039        NaN

               rh   swp total_precip         rad       vpd
0       75.700000  None     0.000000  251.000000  0.396490
1             NaN   NaN          NaN         NaN       NaN

In [1]:
a = combined_data[1]

NameError: name 'combined_data' is not defined

In [12]:
np.asarray(a['stem_radius'])

array([Decimal('3054.553158'), Decimal('3053.101185'),
       Decimal('3051.026983'), ..., Decimal('6456.276486'),
       Decimal('6456.298828'), Decimal('6456.886800')], dtype=object)

In [35]:
a

,series_id,site_id,ts,stem_radius,temp,rh,swp,total_precip,rad,vpd
0,1.0,1.0,2014-05-21 12:40:00,2249.375700,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,1.0,2014-05-21 12:50:00,2248.375100,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,1.0,2014-05-21 13:00:00,2245.998500,21.500000,34.833330,-10.292638,0.000000,622.552230,1.676604
3,1.0,1.0,2014-05-21 13:10:00,2243.332800,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,1.0,2014-05-21 13:20:00,2242.045700,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
440420,1.0,1.0,2022-10-05 00:00:00,4969.418799,8.500000,51.833333,-11.325561,0.000000,0.000000,0.536419
440421,1.0,1.0,2022-10-05 00:10:00,4969.418799,NaN,NaN,NaN,NaN,NaN,NaN
440422,1.0,1.0,2022-10-05 00:20:00,4969.418799,NaN,NaN,NaN,NaN,NaN,NaN
440423,1.0,1.0,2022-10-05 00:30:00,4969.418799,NaN,NaN,NaN,NaN,NaN,NaN
440424,1.0,1.0,2022-10-05 00:40:00,4969.418799,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
a['series_id'] = a['series_id'].ffill().bfill()

In [48]:
a['series_id'].astype(int)

0         1
1         1
2         1
3         1
4         1
         ..
440420    1
440421    1
440422    1
440423    1
440424    1
Name: series_id, Length: 440425, dtype: int64

In [40]:
index_names = meta.loc[ meta['tree_species'].isin(['aria', 'decidua', 'robur']) ].series_id.to_list()
metadata = meta[meta.series_id.isin(index_names) == False].reset_index(drop=True)  # NOTE: removes rare species from metadata

In [41]:
metadata

,measure_point,series_id,series_start,series_stop,series_cutout,series_active,series_display,variable_id,variable_name,variable_resolution,...,site_annual_rad,site_growth_rad,site_annual_relh,site_growth_relh,site_annual_vpd,site_growth_vpd,site_n_depo,site_ozon,site_nfk,site_temp_ref
0,alvaneu-high_dendrometer_µm_n3_0_1.5_south_psy...,1,2014-05-21,2022-10-05,None,no,no,3,tree stem radius change,10,...,166.52,243.83,70.81,70.57,0.30,0.48,None,None,106.00,1178.0
1,alvaneu-high_dendrometer_µm_n4_0_1.5_south_psy...,2,2014-05-21,2022-10-05,None,no,no,3,tree stem radius change,10,...,166.52,243.83,70.81,70.57,0.30,0.48,None,None,106.00,1178.0
2,alvaneu-low_dendrometer_µm_n1_0_1.5_south_psyl...,3,2014-05-21,2022-10-05,None,no,no,3,tree stem radius change,10,...,164.93,239.27,70.23,69.62,0.33,0.51,None,None,191.00,1178.0
3,alvaneu-low_dendrometer_µm_n2_0_1.5_south_psyl...,4,2014-05-21,2022-10-05,None,no,no,3,tree stem radius change,10,...,164.93,239.27,70.23,69.62,0.33,0.51,None,None,191.00,1178.0
4,bachtel-forest_precipitation_mm_meteo_-999_2_b...,5,2012-08-24,2022-09-28,None,no,no,10,precipitation,10,...,137.28,223.03,77.13,74.20,0.30,0.50,None,None,None,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1798,mund-dry_soil_wp_kpa_-999_-999_-15_soil_--999,1873,2024-05-29,NaT,None,yes,yes,32,soil water potential,10,...,164.11,255.25,68.01,63.29,0.45,0.75,None,None,None,1722.0
1799,mund-dry_soil_temp_°c_-999_-999_-50_soil_--999,1874,2024-05-29,NaT,None,yes,yes,29,soil temperature,10,...,164.11,255.25,68.01,63.29,0.45,0.75,None,None,None,1722.0
1800,mund-dry_soil_wp_kpa_-999_-999_-50_soil_--999,1875,2024-05-29,NaT,None,yes,yes,32,soil water potential,10,...,164.11,255.25,68.01,63.29,0.45,0.75,None,None,None,1722.0
1801,mund-dry_soil_temp_°c_-999_-999_-100_soil_--999,1876,2024-05-29,NaT,None,yes,yes,29,soil temperature,10,...,164.11,255.25,68.01,63.29,0.45,0.75,None,None,None,1722.0
1802,mund-dry_soil_wp_kpa_-999_-999_-100_soil_--999,1877,2024-05-29,NaT,None,yes,yes,32,soil water potential,10,...,164.11,255.25,68.01,63.29,0.45,0.75,None,None,None,1722.0

In [22]:
for row in meta.iterrows():
    if row[1].variable_name == 'tree stem radius change':
        print('series id: ' + str(row[1].series_id))
    else:
        print('skip')

series id: 1
series id: 2
series id: 3
series id: 4
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 18
series id: 19
series id: 20
series id: 21
series id: 22
series id: 23
series id: 24
skip
skip
series id: 27
series id: 28
series id: 29
series id: 30
series id: 31
series id: 32
skip
skip
series id: 35
skip
skip
skip
skip
skip
skip
series id: 42
skip
skip
series id: 45
skip
skip
series id: 48
skip
skip
skip
skip
series id: 53
series id: 54
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 72
series id: 73
series id: 74
series id: 75
skip
skip
skip
skip
skip
skip
skip
series id: 83
series id: 84
skip
series id: 86
series id: 87
series id: 88
series id: 89
series id: 90
skip
skip
skip
skip
series id: 95
skip
skip
series id: 98
skip
skip
series id: 101
skip
skip
series id: 104
skip
skip
skip
skip
series id: 109
skip
skip
series id: 112
skip
skip
series id: 115
skip
skip
skip
skip
series id: 120
series id: 121
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 136
series id: 137
series id: 138
series id: 139
series id: 140
skip
skip
skip
skip
series id: 147
skip
skip
skip
skip
series id: 152
series id: 153
skip
skip
series id: 156
series id: 157
skip
skip
series id: 160
series id: 161
series id: 162
series id: 163
skip
skip
series id: 166
series id: 167
series id: 168
series id: 169
skip
skip
series id: 172
series id: 173
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 192
series id: 193
series id: 194
series id: 195
skip
skip
skip
skip
series id: 200
series id: 201
series id: 202
series id: 203
series id: 204
series id: 205
series id: 206
series id: 207
series id: 208
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 221
series id: 222
series id: 223
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 270
series id: 271
series id: 272
series id: 273
series id: 274
series id: 275
series id: 276
series id: 277
series id: 278
series id: 279
series id: 280
series id: 281
series id: 282
series id: 283
series id: 284
series id: 285
series id: 286
series id: 287
series id: 288
skip
skip
skip
skip
skip
skip
skip
series id: 296
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 320
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 339
series id: 340
series id: 341
series id: 342
series id: 343
series id: 344
series id: 345
series id: 346
series id: 347
series id: 348
series id: 349
series id: 350
series id: 351
series id: 352
series id: 353
series id: 354
series id: 355
series id: 356
series id: 357
series id: 358
skip
series id: 360
series id: 361
skip
skip
skip
skip
skip
skip
series id: 368
skip
skip
series id: 371
skip
skip
series id: 374
skip
skip
series id: 377
series id: 378
series id: 379
series id: 380
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 405
series id: 406
series id: 407
series id: 408
series id: 409
series id: 410
series id: 411
series id: 412
skip
skip
skip
skip
skip
skip
skip
series id: 420
series id: 421
series id: 422
series id: 423
series id: 424
series id: 425
series id: 426
series id: 427
series id: 428
series id: 429
series id: 430
series id: 431
series id: 432
series id: 433
series id: 434
series id: 435
series id: 436
series id: 437
series id: 438
series id: 439
series id: 440
series id: 441
series id: 442
series id: 443
series id: 444
series id: 445
series id: 446
series id: 447
series id: 448
skip
skip
series id: 451
series id: 452
series id: 453
series id: 454
series id: 455
series id: 456
series id: 457
series id: 458
series id: 459
series id: 460
series id: 461
series id: 462
series id: 463
series id: 464
series id: 465
series id: 466
series id: 467
series id: 468
series id: 469
series id: 470
series id: 471
series id: 472
series id: 473
series id: 474
series id: 475
series id: 476
series id: 477
series id: 478
series id: 479
series id: 480
series id: 481
series id: 482
series id: 483
series id: 484
series id: 485
series id: 486
series id: 487
series id: 488
series id: 490
series id: 491
series id: 492
series id: 493
series id: 494
series id: 495
series id: 496
series id: 497
series id: 498
series id: 499
series id: 500
series id: 501
series id: 502
series id: 503
series id: 504
series id: 505
series id: 506
series id: 507
series id: 508
series id: 509
series id: 510
series id: 511
series id: 512
series id: 513
series id: 514
series id: 515
series id: 516
series id: 517
series id: 518
series id: 519
series id: 520
series id: 521
series id: 522
series id: 523
series id: 524
series id: 525
series id: 526
series id: 527
series id: 528
series id: 529
series id: 530
skip
skip
skip
skip
skip
skip
series id: 537
series id: 538
series id: 539
series id: 540
series id: 541
series id: 542
series id: 543
series id: 544
series id: 545
series id: 546
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 557
series id: 558
skip
skip
skip
series id: 562
series id: 563
skip
skip
skip
skip
skip
series id: 569
skip
skip
series id: 572
series id: 573
series id: 574
series id: 575
series id: 576
series id: 577
skip
skip
skip
skip
skip
skip
skip
skip
series id: 586
series id: 587
series id: 588
series id: 589
series id: 590
series id: 591
series id: 592
series id: 593
series id: 594
series id: 595
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 661
series id: 662
series id: 663
series id: 664
series id: 665
series id: 666
series id: 667
series id: 668
series id: 669
series id: 670
series id: 671
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 682
series id: 683
series id: 684
series id: 685
series id: 686
series id: 687
series id: 688
series id: 689
series id: 690
series id: 691
series id: 692
series id: 693
skip
skip
series id: 696
series id: 697
skip
skip
series id: 700
series id: 701
series id: 702
series id: 703
series id: 704
series id: 705
series id: 706
series id: 707
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 718
series id: 719
series id: 720
series id: 721
series id: 722
series id: 723
series id: 724
series id: 725
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 738
series id: 739
series id: 740
series id: 741
series id: 742
series id: 743
series id: 744
series id: 745
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 756
series id: 757
series id: 758
series id: 759
series id: 760
series id: 761
series id: 762
series id: 763
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 782
series id: 783
series id: 784
series id: 785
series id: 786
series id: 787
series id: 788
series id: 789
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 800
series id: 801
series id: 802
series id: 803
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 814
series id: 815
series id: 816
series id: 817
series id: 818
series id: 819
series id: 820
series id: 821
series id: 822
series id: 823
series id: 824
series id: 825
series id: 826
skip
skip
series id: 829
series id: 830
series id: 831
series id: 832
series id: 833
series id: 834
skip
skip
series id: 837
series id: 838
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 849
series id: 850
skip
skip
series id: 853
series id: 854
series id: 855
series id: 856
series id: 857
series id: 858
series id: 859
series id: 860
series id: 861
series id: 862
series id: 863
series id: 864
series id: 865
series id: 866
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 883
skip
skip
skip
skip
series id: 888
skip
skip
series id: 891
skip
skip
series id: 894
skip
skip
series id: 897
skip
skip
skip
skip
series id: 902
skip
skip
series id: 905
skip
skip
series id: 908
skip
skip
series id: 911
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 922
series id: 923
series id: 924
series id: 925
series id: 926
series id: 927
series id: 928
series id: 929
series id: 930
series id: 931
skip
skip
skip
skip
skip
series id: 937
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 964
series id: 965
skip
skip
skip
skip
series id: 970
series id: 971
series id: 972
series id: 973
series id: 974
series id: 975
series id: 976
series id: 977
series id: 978
series id: 979
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1009
series id: 1010
series id: 1011
series id: 1012
series id: 1013
series id: 1014
series id: 1015
series id: 1016
skip
skip
skip
series id: 1020
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1050
series id: 1051
series id: 1052
series id: 1053
series id: 1054
series id: 1055
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1077
series id: 1078
series id: 1079
series id: 1080
skip
skip
series id: 1083
series id: 1084
series id: 1085
series id: 1086
series id: 1087
series id: 1088
series id: 1089
skip
skip
skip
skip
series id: 1094
series id: 1095
series id: 1096
series id: 1097
series id: 1098
series id: 1099
series id: 1100
series id: 1101
series id: 1102
series id: 1103
series id: 1104
series id: 1105
series id: 1106
series id: 1107
skip
skip
skip
skip
series id: 1112
series id: 1113
series id: 1114
series id: 1115
series id: 1116
series id: 1117
series id: 1118
series id: 1119
skip
skip
skip
skip
skip
series id: 1125
series id: 1126
series id: 1127
series id: 1128
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1142
series id: 1143
series id: 1144
series id: 1145
series id: 1146
series id: 1147
series id: 1148
series id: 1149
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1162
series id: 1163
series id: 1164
skip
skip
series id: 1167
series id: 1168
series id: 1169
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1180
series id: 1181
series id: 1182
series id: 1183
series id: 1184
series id: 1185
series id: 1186
series id: 1187
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1206
series id: 1207
series id: 1208
series id: 1209
series id: 1210
series id: 1211
skip
skip
skip
skip
skip
skip
series id: 1218
series id: 1219
series id: 1220
series id: 1221
series id: 1222
series id: 1223
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1232
series id: 1233
series id: 1234
series id: 1235
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1246
series id: 1247
series id: 1248
series id: 1249
series id: 1250
series id: 1251
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1260
series id: 1261
series id: 1262
series id: 1263
series id: 1264
series id: 1265
skip
skip
series id: 1268
series id: 1269
series id: 1270
series id: 1271
skip
skip
skip
skip
series id: 1276
series id: 1277
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1288
series id: 1289
series id: 1290
series id: 1291
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1300
series id: 1301
series id: 1302
series id: 1303
series id: 1304
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1317
series id: 1318
series id: 1319
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1328
series id: 1329
series id: 1330
series id: 1331
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1340
series id: 1341
series id: 1342
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1351
series id: 1352
series id: 1353
series id: 1354
series id: 1355
series id: 1356
series id: 1357
series id: 1358
series id: 1359
series id: 1360
series id: 1361
series id: 1362
series id: 1363
skip
series id: 1365
series id: 1366
series id: 1367
series id: 1368
series id: 1369
series id: 1370
series id: 1371
series id: 1372
series id: 1373
series id: 1374
skip
skip
skip
skip
skip
skip
series id: 1381
series id: 1382
series id: 1383
series id: 1384
series id: 1385
series id: 1386
skip
skip
skip
skip
series id: 1391
series id: 1392
series id: 1393
series id: 1394
series id: 1395
series id: 1396
series id: 1397
series id: 1398
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1409
skip
skip
skip
skip
series id: 1414
skip
skip
series id: 1417
skip
skip
series id: 1420
skip
skip
series id: 1423
skip
skip
skip
skip
series id: 1430
skip
skip
series id: 1433
skip
skip
series id: 1436
skip
skip
series id: 1439
series id: 1440
series id: 1441
series id: 1442
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1452
skip
skip
series id: 1455
series id: 1456
series id: 1457
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1470
series id: 1471
series id: 1472
skip
skip
skip
skip
skip
skip
series id: 1479
series id: 1480
series id: 1481
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1490
series id: 1491
series id: 1492
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1501
series id: 1502
series id: 1503
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1516
series id: 1517
series id: 1518
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1527
series id: 1528
series id: 1529
skip
skip
skip
skip
skip
skip
series id: 1536
series id: 1537
series id: 1538
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1547
series id: 1548
series id: 1549
series id: 1550
series id: 1551
series id: 1552
series id: 1553
series id: 1554
series id: 1555
series id: 1556
series id: 1557
series id: 1558
series id: 1559
series id: 1560
series id: 1561
series id: 1562
series id: 1563
series id: 1564
series id: 1565
series id: 1566
series id: 1567
series id: 1568
series id: 1569
series id: 1570
series id: 1571
series id: 1572
series id: 1573
series id: 1574
series id: 1575
series id: 1576
series id: 1577
series id: 1578
series id: 1579
series id: 1580
series id: 1581
series id: 1582
series id: 1583
series id: 1584
series id: 1585
series id: 1586
series id: 1587
series id: 1588
series id: 1589
series id: 1590
series id: 1591
series id: 1592
series id: 1593
skip
skip
skip
skip
skip
skip
series id: 1600
series id: 1601
series id: 1602
series id: 1603
series id: 1604
series id: 1605
series id: 1606
series id: 1607
series id: 1608
series id: 1609
series id: 1610
series id: 1611
series id: 1612
series id: 1613
series id: 1614
series id: 1615
series id: 1616
series id: 1617
skip
skip
series id: 1620
series id: 1621
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1630
series id: 1631
series id: 1632
series id: 1633
series id: 1634
series id: 1635
series id: 1636
series id: 1637
series id: 1638
series id: 1639
series id: 1640
series id: 1641
series id: 1642
series id: 1643
series id: 1644
series id: 1645
series id: 1646
series id: 1647
series id: 1648
series id: 1649
series id: 1650
series id: 1651
series id: 1652
series id: 1653
series id: 1654
series id: 1655
series id: 1656
series id: 1657
series id: 1658
series id: 1659
series id: 1660
series id: 1661
series id: 1662
series id: 1663
series id: 1664
series id: 1665
series id: 1666
series id: 1667
series id: 1668
series id: 1669
series id: 1670
series id: 1671
series id: 1672
series id: 1673
series id: 1674
series id: 1675
series id: 1676
series id: 1677
series id: 1678
series id: 1679
series id: 1680
series id: 1681
series id: 1682
series id: 1683
series id: 1684
series id: 1685
series id: 1686
series id: 1687
series id: 1688
series id: 1689
series id: 1690
series id: 1691
series id: 1692
series id: 1693
series id: 1694
series id: 1695
series id: 1696
series id: 1697
series id: 1698
series id: 1699
series id: 1700
series id: 1701
series id: 1702
series id: 1703
series id: 1704
series id: 1705
series id: 1706
series id: 1707
series id: 1708
series id: 1709
series id: 1710
series id: 1711
series id: 1712
series id: 1713
series id: 1714
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1727
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1805
series id: 1806
series id: 1807
series id: 1808
series id: 1809
series id: 1810
series id: 1811
series id: 1812
series id: 1813
series id: 1814
series id: 1815
series id: 1816
series id: 1817
series id: 1820
skip
skip
skip
series id: 1828
series id: 1829
series id: 1830
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
skip
series id: 1853
skip
skip
skip
skip
series id: 1858
series id: 1859
series id: 1860
series id: 1866
series id: 1869
series id: 1870
series id: 1871
skip
skip
skip
skip
skip
skip

In [42]:
array = np.array([1,2,3,4,5,6,7,8,9])

In [48]:
np.concatenate((array[0:3], array[7:9]))

array([1, 2, 3, 8, 9])

In [46]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])